---
editor_options: 
  markdown: 
    wrap: 72
---

# Cerebrovascular

**UNDER CONSTRUCTION - This Chapter is Currently in DRAFT mode**

**07 Jan 2019:** *Adam Johnson, MD, MPH; Nicole Rich, MD, MPH; Kevin
Kniery, MD, MPH*

```{r echo=FALSE}

library(embedr)

embed_audio("https://traffic.libsyn.com/audiblebleeding/E7_-_Carotid_VSITE.mp3")

```

## Available Guidelines

[Society for Vascular Surgery clinical practice guidelines for
management of extracranial cerebrovascular
disease](https://www.jvascsurg.org/article/S0741-5214(21)00893-4/fulltext)
[@aburahmaSocietyVascularSurgery2022]

## Presentation and Diagnosis

1.  **What is the definition of crescendo TIAs?**

    The presenting symptoms of extracranial carotid disease is of the
    utmost importance to understand. Focal neurologic symptoms that
    occur suddenly and then resolve within 24 hours are called a
    transient ischemic attach (TIA). If the deficit persists beyond 24
    hours, then it is considered a stroke. Strokes are then graded
    according to the National Institute of Health Stroke Scale
    (NIHSS).[@fischer2010]

    A particularly confusing distinction is between a crescendo TIA and
    a stroke in evolution. A crescendo TIA is frequent repetitive neurological
    attacks without complete resolution of the deficit between the
    episodes, usually over a 24 hour period. The result of which is the
    same neurological deficit. If the patient exhibits progressive
    deterioration in neurological function between TIA episodes this is
    classified as a stroke in evolution not a crescendo TIA.[@ricotta]
    These are both particularly concerning findings and may be an
    indication for an emergent intervention.

2.  **Who needs to be screened for carotid disease?**

    Not everyone should be screened for carotid disease, however, as
    only 15% of patients who have a stroke experience a warning TIA
    prior to their event, there is merit in screening high risk
    patients.[@rockman2019] The purpose of carotid bifurcation imaging
    is to detect "stroke-prone" carotid bifurcation plaque and identify
    a high-risk patient likely to benefit from therapy designed to
    reduce stroke risk.

    Traditionally, the clinical sign associated with asymptomatic
    carotid stenosis is the presence of a neck bruit on auscultation.
    Focal ipsilateral carotid bruits in symptomatic patients has a
    sensitivity of 63% and a specificity of 61% for high-grade carotid
    stenosis (range, 70%-99%). As these figures suggest the absence of
    carotid bruit does not absolutely exclude the presence of a
    significant carotid bifurcation lesion, therefore additional
    criteria are used to determine which patients would benefit from
    screening:

    -   Evidence of clinically significant peripheral vascular disease
        regardless of age

    -   Patients aged \>65 years with a history of one or more of the
        following atherosclerotic risk factors:

        -   CAD

        -   Smoking

        -   Hypercholesterolemia

    In general, the more risk factors present, the higher the yield of
    screening for the patient. Presence of a carotid bruit, AAA or
    family history of disease alone is not sufficient to warrant
    imaging.[@aburahma2022]

3.  **Ultrasound Imaging**

    -   US is considered the best, least invasive, and cost effective
        method for detecting carotid stenosis on
        screening.[@shaalan2008] For more see \@ref(extracranial).

    -   50-69% stenosis of ICA - US has a low sensitivity for 50-69%
        stenosis. A negative ultrasound in symptomatic patients
        necessitates additional imaging. Typically on scanning if 50-69%
        ICA stenosis is present:

        -   PSV 125-229 cm/sec
        -   EDV 40-100
        -   Internal/Common Carotid PSV Ratio 2-4

    -   70-99% stenosis of ICA- Typically on scanning:

        -   PSV \>/= 230 cm/sec

        -   EDV \>100 (EDV \> 140 cm/sec most sensitive for stenosis
            \>80%)

        -   Internal/Common Carotid PSV Ratio \> 4

    -   Velocity-based estimation of carotid artery stenosis may need to
        be adjusted in certain circumstances:

        -   Higher velocities in women than in men.

        -   Higher velocities in the presence of contralateral carotid
            artery occlusion.

    -   High carotid bifurcation, severe arterial tortuosity, extensive
        vascular calcification, and obesity may also reduce the accuracy
        of US imaging.

4.  **Other Imaging Modalities**

    -   CTA

        -   Pro - fast, sub-millimeter spatial resolution, visualize
            surrounding structures.

        -   Con - cost, contrast exposure.

    -   MRA

        -   Pro - no contrast administered; can analyze plaque
            morphology.

        -   Con - Does not visualize calcium in plaque; overestimates
            the degree of stenosis (False positive for 50-69% to be read
            as \>70%).

    -   Catheter-based digital subtraction imaging (DSA)

        -   Still considered by many the gold-standard imaging modality.

        -   Reserved for individuals with conflicting less-invasive
            imaging or those considered for CAS.

        -   Con - cost, contrast, and risk of stroke.

## Management

### Medical Management - Asymptomatic Patients

First line management for asymptomatic patients with carotid stenosis is
medical optimization of risk factors. The benefit of prophylactic
intervention (CEA/CAS) of even high grade stenosis is estimated at a
1-2% stroke reduction risk per year.
[@naylorWhyManagementAsymptomatic2015] In addition, keep in mind that
intervention (CEA/CAS) has only demonstrated a benefit in asymptomatic
patient with life expectancy greater than 3 years.
[@bulbuliaAsymptomaticCarotidSurgery2017;
@halliday10yearStrokePrevention2010;
@rosenfieldRandomizedTrialStent2016]

**Hypertension**

-   Blood pressure reduction, with a target of \<140/90 mmHg through
    lifestyle interventions and anti-hypertensive treatment is
    recommended in individuals who have hypertension with asymptomatic
    carotid atherosclerosis or those with TIA or stroke after the
    hyper-acute period.

-   Each 10-mm Hg reduction in blood pressure among hypertensive
    patients decreases the risk of stroke by 33% in patients aged
    60-79.[@aiyagari2009]

**Diabetes**

-   In diabetic patients glycaemic control to nearly normoglycemic
    levels (target hemoglobin A1C \<7%) is recommended to reduce
    microvascular complications and, with a smaller evidence base,
    macrovascular complications other than stroke.[@ricotta]

**Hypercholesterolaemia**

-   Statin agents are recommended targeting LDL of 100 mg/dL, for those
    with coronary heart disease or symptomatic atherosclerotic disease,
    and LDL of 70 mg/dL for very high-risk persons with multiple risk
    factors.

-   High dose statin therapy in patients with TIA/stroke reduce future
    rates of stroke or cardiovascular events but not overall mortality
    at 5 years. [@karamHighDoseAtorvastatinStroke2008]

**Smoking Cessation** - Encouraging smoking cessation is paramount for
these patients. Smoking and carotid disease have been found to have a
dose dependent relationship based on pack-years. Risk of stroke has been
shown to reduce to baseline within 2-4 years of smoking
cessation.[@hicks2015; @kawachi1993; @petrik1995; @wilson1997]

**Antiplatelet therapy** - Single agent antiplatelet therapy, most often
aspirin, is often all that is needed, but this should be weighted with
other cardiovascular risk factors. A number of trials have showed
limited benefit of adding an additional antiplatelet or routinely
testing for clopidogrel resistance.[@ricotta]

### Medical Management - Symptomatic Patients

Patients who present with a TIA should be placed on dual antiplatelet
therapy, often aspirin and clopidogrel, which are continued through the
workup and treatment of carotid disease. Patients often also have their
blood pressure medications reduced to allow permissive hypertension and
maximize perfusion to at risk cerebral tissue.

While we are not often directly involved in the management of acute
stroke, vascular surgeons should be aware of best practices in this
area. Management of acute stroke currently follow these
timelines[@powers2018GuidelinesEarly2018]

-   \< 4.5 hours from onset of symptoms - medical thrombolysis with tPA
    unless contraindicated.

    -   Patient age \>80 and diabetes are contraindications to tPA
        administration after 3hrs.
    -   Other contraindications include - hypertension, intracranial
        hemorrhage, recent stroke or cranial trauma, spine/brain surgery
        within 3 months, GI bleed within 21 days.

-   \<6 hours from onset of symptoms - catheter directed therapy

-   After 6 hours, there is limited benefit to thrombolytic therapy.

### Surgery - Carotid Endarterectomy

**Indications for Surgical Intervention**

-   Recommendations on when to operate after a TIA/stroke.

    -   Acute stroke with a fixed neurologic deficit of \>6h duration -
        When the patient is medically stable, intervention in 14 days or
        less after stroke is preferable.
        [@rothwellEndarterectomySymptomaticCarotid2004;
        @meershoekTimingCarotidIntervention2018]

    -   Consider urgent intervention in a medically stable patient with
        mild-moderate neurologic deficit, if there is a significant area
        of ischemic penumbra at risk for progression on imaging that is
        contributing to the patient's presentation.

    -   Stroke in evolution (fluctuating / evolving neurological
        deficit) or crescendo TIA (repetitive transient ischemia with
        improvement between events) - If the patient's neurological
        status is not stabilized by medical intervention then an urgent
        CEA should be considered.

    -   In this clinical context CEA is preferred to CAS based on an
        increased embolic potential of carotid lesions.
        [@rantnerEarlyEndarterectomyCarries2017]

-   What is the only emergent indication for CEA?

    -   Crescendo TIAs or a stroke in evolution with a surgically
        correctable lesion identified on imaging.

**CEA Intraoperative Techniques**

-   General concepts

    -   Patch angioplasty or eversion endarterectomy are recommended
        over primary arterial closure due to decreased ipsilateral
        stroke, perioperative carotid occlusion, return to the operating
        room, restenosis and 1-year stroke rates.[@goodney2010;
        @rerkasem2009] Patch repair is considered the standard of care
        surgical management for most extracranial carotid
        lesions.[@arnold2019]

-   Neuromonitoring/Shunting options during a carotid
    endarterectomy[@chongruksut2014; @wiske2018]

    -   Local/regional anesthesia with direct neurological monitoring -
        the benefit being that the patient is awake and moving to
        command throughout the case. Indications for shunting include
        lateralizing deficits, seizure, lack of consciousness and severe
        anxiety. Improved neuromonitoring, however, has not been shown
        to reduce myocardial infarction rate with CEA.

    -   Stump pressure- Clamp the inflow and place a butterfly attached
        to a-line tubing into the internal carotid artery. If the stump
        pressure is \> 50 mmHg the surgeon can chose to proceed without
        shunt placement, if \< 50mmHg then a shunt should be placed
        prior to proceeding.

    -   EEG Neuromonitoring - EEG tech places neuromonitoring, monitored
        by the technician and neurologist remotely intraoperatively.
        Generally the surgeon should clamp the ICA for 3 minutes before
        proceeding, if the patient develops neurological deficit/EEG
        abnormalities with slowing and decreased alpha and beta waves,
        then unclamp, await normalization of EEG, then proceed.

    -   Cerebral Oximetry - 15% decrease in either hemisphere should be
        shunted.

    -   Transcranial Doppler (TCD) - severe slowing in the middle
        cerebral artery. An RCT demonstrated that TCD and cerebral
        oximetry changes most accurately predicted cerebral ischemia.
        Detection of a greater than 50% drop in middle cerebral artery
        velocity using transcranial Doppler is 100% sensitive for
        detecting cerebral ischemia. [@moritz2007] For more see
        \@ref(intracranial).

    -   Non-selective shunting - the surgeon uses a shunt for all CEAs
        as standard practice, this is often done for all CEAs performed
        under general anesthesia

-   Techniques to reach high internal carotid lesions?[@beretta2006]

    -   A good knowledge of the available imaging while preparing for
        the procedure is essential when considering the level of the
        carotid bifurcation.

    -   Nasotracheal intubation will allow for jaw closure and neck
        extension to facilitate exposure of higher lesions.

    -   Division of the posterior belly of the digastric muscle,
        stylopharyngeal muscle, styloglossus muscle, stylomandibular
        ligament or the styloid process. Care should be taken to
        identify and preserve the glossopharyngeal nerve.

    -   Division of the occipital artery.

    -   Dissection along the posterior parotid gland.

    -   ENT surgeon assisted mandible subluxation with assistance if
        previous techniques fail.

-   What is the best technique for a patient with an anatomically kinked
    internal carotid artery?

    -   Eversion carotid endarterectomy (only indication for selection
        for this technique over patch endarterectomy), transection
        allows for reduction of redundancy at re-anastamosis.

    -   Otherwise, no advantage has been shown between eversion or
        patch, both can be shunted.

-   Nerve Injuries -- where you would encounter these and, if injured,
    what deficit would be seen?

    -   Hypoglossal: Most commonly injured. Usually passes above the
        bifurcation of the carotid artery. If injured the tongue will
        deviate toward the side of injury on protrusion.

    -   Glossopharyngeal: Commonly injured during high dissections.
        Found under the posterior digastric muscle. Injury can be
        devastating for patients resulting in difficulty swallowing and
        high aspiration risk.

    -   Vagus: Usually found adjacent and lateral to the common carotid.
        Injury can occur with carotid clamping. Patients develop
        hoarseness due to innervation of the laryngeal muscles from the
        recurrent laryngeal nerve which is a branch of the vagus.

    -   Marginal Mandibular: Branch of the facial nerve. Runs inferiorly
        to the angle of the mandible. Commonly a retraction injury
        during high dissections leading to the corner of the ipsilateral
        lip drooping, can be confused with a significant neurological
        deficit following the case.

-   Completion duplex for CEA

    -   Can identify technical issues with carotid endarterectomy such
        as clamp site injury, thrombosis, intimal flap or dissection, or
        missed disease.[@lipski1996]

        -   Acute thrombus may be hypoechoic and difficult to see on
            B-mode, color flow necessary to determine luminal narrowing
            or occlusion. For more see \@ref(extracranial).

    -   Revision required if residual plaque identified with severe
        velocity elevation.[@weinstein2015]

        -   Elevated velocities can be seen for many reasons that do not
            require revision, including incorrect technique (compression
            with probe), tortuosity, size discrepancy, ICA
            spasm.[@ricco2013; @weinstein2015]

    -   One study demonstrated that 2.3% of carotids required revision
        for concerning findings on completion duplex
        ultrasound.[@ascher2004]

**Postoperative Complications**

-   What to do if the patient develops neuro deficits following carotid
    endarterectomy: Two main concerns- an intimal flap causing
    thrombosis or an embolic event resulting in a stroke. Perform a
    thorough neurological exam to confirm in operated carotid territory.

    -   If in OR -- perform duplex, very low threshold to re-explore and
        confirm patency of ICA with duplex or doppler. If ICA open and
        concerned for distal embolization, then perform a cerebral
        angiogram and proceed with thrombolysis or
        thrombectomy.[@fletcher2016]

    -   If in Recovery or on the floor -- many would consider CTA first
        line vs duplex to look for thrombosis.

-   Risk factors and how to manage hyperperfusion syndrome?

    -   Defined as an ipsilateral headache, hypertension, neurological
        deficits likely in distribution of the carotid which can
        progress to seizures and intracranial hemorrhage (75-100%
        mortality). Can present 2-3 days post surgery.[@kaku2004]

    -   Patients with uncontrolled hypertension are at risk for
        hyperperfusion syndrome, clinical practice guidelines from SVS
        recommend strict BP control following CEA, with target pressure
        being less than 140/80mmHg or 20mmHg from preoperative
        baseline.[@abou-chebl2004]

-   High risk groups

    -   ESRD patients have higher rates of perioperative stroke, but
        also have higher rates of stroke if not revascularized.
        [@klarinPerioperativeLongtermImpact2016]

**Long term complications and follow up**

-   Recommend f/u US duplex of bilateral carotids at \</=30 days. \>/=
    50% stenosis further imaging is indicated.

-   Ipsilateral stenosis

    -   0-3mo likely due to inadequate endarterectomy or clamp
        injury.[@kang2014]

    -   1-3y likely neointimal hyperplasia, smooth and regular. If \<80%
        stenosis and asymptomatic, then duplex surveillance and
        antiplatelet. If progresses, then often endo treatment
        first.[@garzon-muvdi2016]

-   Contralateral stenosis:

    -   The risk of progression for moderate stenosis at the initial
        surveillance to severe stenosis in the contralateral artery can
        be as high as 5 times.

    -   Requires post-operative surveillance.

-   Carotid artery patch infections

    -   Rare complication (\<1%) presenting as phlegmon, pseudoaneurysm,
        sinus tract or carotid cutaneous fistula.[@stone2011]

    -   Treatment is excision and replacement with autologous
        tissue.[@fatima2019]

### Endovascular - Carotid Artery Stenting

-   In patients aged \>70 the risk of intra- or post procedure stroke
    was the highest, if undergoing CAS, presumably due to calcified
    disease in the arch.

    -   Lesion-specific characteristics are thought to increase the risk
        of cerebral vascular events after CAS and include a "soft"
        lipid-rich plaque identified on noninvasive imaging, extensive
        (15 mm or more) disease, a pre-occlusive lesion, and
        circumferential heavy calcification.

    -   This risk can be reduced, but not eliminated, by using
        flow-reversal embolic protection rather than distal filter
        protection.

-   Limited data is available on CAS in asymptomatic patients -
    currently is not supported by guidelines or considered reimbursable.

-   Consider CAS in symptomatic patients with \>50% stenosis who are
    poor candidates for CEA due to severe uncorrectable medical
    comorbidities and/or anatomic considerations:

    -   Ipsilateral neck dissection or XRT - equivalent periprocedural
        stroke rate to CEA, but increased later stroke rate. CEA higher
        rates of cranial nerve damage (9%).
        [@giannopoulosRevascularizationRadiationinducedCarotid2018]

    -   Contralateral vocal cord paralysis.

    -   Lesions that extend proximally to the clavicle or distal to C2.

-   Transfemoral Approach vs Transcarotid approach

    -   ROADSTER Trial - single arm study with flow reversal for
        cerebral protection. Suggested lower rates of post-op stroke in
        patients undergoing TCAR.
    -   TCAR contraindications include previous CCA intervention, CCA
        disease at entry site, \<5cm CCA (clavicle to bifurcation) for
        sheath, CCA \< 6mm, contralateral recurrent laryngeal or vagus
        nerve injury.[@kwolek2015]
    -   Patient needs to be preloaded with dual antiplatelet medications
        for at least 5-7d, should delay procedure if has not been
        appropriately loaded with antiplatelets.[@brott2010;
        @kwolek2015; @valls2017]
    -   Studies with TCD have shown that there may be reduced
        embolization rates with TCAR over transfemoral
        stenting.[@plessers2016]

-   Complications

    -   Post stenting ICA thrombosis should first be treated with
        abciximab and catheter directed thrombolysis, followed by
        endo-salvage with suction thrombectomy, repeat angioplasty or
        stenting. May require eventual conversion to CEA.[@coelho2019;
        @naylor2018]

-   Post-CAS follow up - Dual-platelet therapy should be continued for 1
    month after the procedure, and aspirin should be continued
    indefinitely.

    -   In stent restenosis (\>50%) - 4-times higher rate of stroke than
        no recurrence of disease, but more benign than de novo
        disease.[@clavel2019] Stenosis should be confirmed with CTA. No
        clear difference between treatments in literature - PBA,
        Cutting, DBA, stenting, open conversion.[@arhuidese2017] Repeat
        angioplasty or stent have low incidence of periprocedural stroke
        but failed to improve long term stroke/death/MI or patency
        rates.[@chungPercutaneousInterventionCarotid2016a]

### Summary of Prospective Trials

1.  Asymptomatic Carotid Atherosclerosis Study (ACAS)

    -   Compared medical management with CEA in asymptomatic patients
        with \> 60% stenosis.

    -   5-year stroke and death rate was 5.1% vs 11%.

    -   In women, the benefit of CEA was not as certain as 5y stroke and
        death rates were 7.3% vs. 8.7%.

    -   This trial was conducted pre-statin and clopidogrel era.

2.  North American Symptomatic Carotid Endarterectomy Trial (NASCET)
    [@northamericansymptomaticcarotidendarterectomytrialcollaboratorsBeneficialEffectCarotid1991]

    -   Compared medical management vs CEA for symptomatic patients with
        moderate (50-69%) and severe stenosis (\>70%)

    -   Only moderate impact for patients with moderate stenosis
        (50-69%)

    -   Symptomatic patients with \>70 % stenosis benefited from CEA, at
        18 months 7% major stroke in surgical arm, and a 24% stroke rate
        in medical arm. 29% reduction in 5-year risk of stroke or death.

        -   Patients with severe \>70% stenosis had such a dramatic
            effect the trial was stopped early for this subset and all
            referred for endarterectomy.

    -   No benefit is shown in symptomatic patients with \< 50% stenosis

    -   European studies have shown similar results

        -   ACST = ACAS

        -   ECST = NASCET.

    -   **Take a listen!** [Click hear to listen to Dr. William Jordan
        discuss this landmark
        paper!](https://www.audiblebleeding.com/2021/09/29/landmark-papers-nascet/)

3.  Carotid Revascularization Endarterectomy versus Stenting Trial
    (CREST).[@silver2011]

    -   Compared CEA vs. CAS in both symptomatic and asymptomatic
        patients.

    -   Composite endpoint of 30-day stroke, MI, death equivalent
        between CEA and CAS.

    -   CAS had a significantly higher incidence of stroke and death
        than CEA and CEA higher incidence of MI.

        -   Follow up at 10 years demonstrated no difference in
            composite stroke/MI/death but increased rate of stroke/death
            in stented patients likely attributable to increased
            periprocedural stroke. [@brottLongTermResultsStenting2016b]
        -   CAS patients with stroke had a higher impact on QOL than CEA
            patients with MI.[@brott2010; @redfern2011; @mantese2010]

    -   Subanalyses identified that older patients (\>70y) had better
        outcomes after CEA than CAS, the QOL impact of stroke was more
        significant than that of MI, and anatomic characteristics of
        carotid lesions (longer, sequential, remote) were predictive of
        increased stroke and death after CAS.

    -   Unfortunately, this study provides a benchmark to strive for,
        but no other large trials have achieved these results.

4.  ROADSTER[@kwolek2015]

    -   Single arm feasibility trial of transcarotid carotid stenting.

    -   The results of the ROADSTER trial demonstrate that the use of
        the ENROUTE Transcarotid NPS is safe and effective at preventing
        stroke during CAS. The overall stroke rate of 1.4% is the lowest
        reported to date for any prospective, multicenter clinical trial
        of CAS (i.e. CREST). No direct comparison.

5.  Trials to look out for in the next few years:

    -   CREST-2 - a multicenter, randomized controlled trial underway
        evaluating revascularization against modern intensive medical
        management.

    -   ACT-1 and ACST-2- the role of intervention in asymptomatic
        patients, designed to compare the early and long-term results of
        CEA vs CAS and best medical management.

    -   ROADSTER-2 - TCAR.

## Uncommon Carotid Disease

### Complicated Extracranial Occlusive Disease

-   Occluded Carotid: What is the management of an occluded carotid?

    -   Leave it alone.

-   What if an occluded carotid on imaging is still causing TIAs?

    -   Ongoing symptoms in the setting of carotid occlusion is known as
        carotid artery stump syndrome. Symptoms are likely due to emboli
        from friable intima of the internal carotid or from the external
        carotid through collaterals. Treatment is external carotid
        endarterectomy and ligation of the internal carotid.[@hrbác2012]

    -   The addition of oral anticoagulation is likely to reduce the
        rate of recurrent stroke.

-   Simultaneous coronary and carotid disease

    -   Patients with symptomatic carotid stenosis will benefit from CEA
        before or concomitant with CABG. The timing of the intervention
        depends on the clinical presentation and institutional
        experience (GRADE 1, Level of Evidence B).

    -   Patients with severe bilateral asymptomatic carotid stenosis,
        including stenosis and contralateral occlusion, should be
        considered for CEA before or concomitant with CABG (GRADE 2,
        Level of Evidence B).

    -   Patients undergoing simultaneous CEA/CABG demonstrate highest
        mortality. [@naylorSystematicReviewOutcomes2003]

-   What about tandem lesions in the carotid in a symptomatic patient,
    carotid bulb and carotid siphon lesion (high ICA)? How should you
    treat this?

    -   Treat carotid bulb and extracranial disease first, likely to be
        the embolic source.
    -   Treatment of intracranial disease has been shown to increase
        rates of stroke and death.[@chimowitz2011]. Extracranial to
        intracranial bypass has increased risk of stroke over
        BMT.[@ec/icbypassstudygroup1985]

-   What if the patient has severe vertebrobasilar insufficiency and
    carotid artery disease?

    -   Should undergo carotid revascularization first to improve flow.
        Then reassess for vertebrobasilar insufficiency.
    -   Vertebrobasilar insufficiency characterized by dizziness,
        ataxia, nausea, vertigo and bilateral weakness.
        [@limanetoPathophysiologyDiagnosisVertebrobasilar2017;
        @nouh2014]

### Vertebrobasilar Disease

-   How do you treat isolated vertebral disease?

    -   Most common etiology is atherosclerosis, but can also be caused
        by embolism, dissection or migraines.[@limaneto2017]
    -   Symptomatic primary vertebral disease with \>60% stenosis should
        be treated. Vertebral divided into segments. V1 preforaminal
        (lower than C6), V2 foraminal (C6-C2), V3 (C2-dura), V4
        (intracranial).[@morasch2019; @berguer1998]
    -   Disease of V1 should be treated with vertebral transposition of
        bypass with vein.[@rangel-castilla2015]
        -   Most common complication is Horner's Syndrome due to
            disruption of the sympathetic chain (20%), next is TIA
            (1-3%).[@coleman2013; @ramirez2012]
    -   Disease of V2 is most difficult to access and should be treated
        with bypass from ICA to V3.[@berguer1985]
    -   RCT of BMT vs endo treatment did not show superiority of endo
        treatment, recurrent symptoms most common, periprocedural stroke
        was rare.[@antoniou2012; @coward2007]

### Carotid artery dissection

-   Patients with carotid dissection should be initially treated with
    antithrombotic therapy (antiplatelet agents or anticoagulation)
    (GRADE 1, Level of Evidence C).
-   Indications for endovascular treatment of carotid artery dissection
    [@cohenSinglecenterExperienceEndovascular2012;
    @markusAntiplateletTherapyVs2019a;
    @phamEndovascularStentingExtracranial2011]
    -   Ongoing symptoms on best medical therapy

    -   Contraindication to antithrombotics

    -   Pseudoaneurysm

### Internal Carotid Artery Aneurysms

-   Defined as dilation of the bulb 200% of the internal carotid artery
    or 150% of the common carotid artery. Like popliteal aneurysms the
    major risk is thromboembolization.[@bush2019; @fankhauser2015;
    @pourier2018]

-   Treatment is resection with primary repair or interposition.
    Distorted anatomy increased the risk for cranial nerve injury
    (12%).[@welleweerd2015]

-   Redundant ICA - should be repaired if patient symptomatic due to
    kinking. Treated with resection and primary repair with shortening
    and straightening.[@ballotta2005]

-   Fibromuscular Dysplasia (FMD)[@olin2011] - for more, see
    \@ref(fibromuscular-dysplasia-fmd)

    -   Asymptomatic disease can often be treated with antiplatelets
        alone.

    -   Duplex ultrasound demonstrates classic "chain of lakes"
        appearance. For more see \@ref(extracranial)

    -   Associated with intracranial aneurysms (13%), therefore may be
        reasonable to also pursue brain imaging if identified. However,
        no formal guidelines exist.[@lather2017]

### Carotid Body Tumors (CBT)

Shamblin criteria utilized to determine difficulty of resection and is
associated with rates of carotid reconstruction or cranial nerve injury.

Blood supply primarily from the external carotid artery.[@robertson2019;
@davila2016] Embolization helps reduce risk of perioperative blood loss
not associated with reduced cranial nerve injury.  Resection 24-36hrs
after embolization.[@power2012]

One quarter (25%) are associated with a germline mutation or familial
history. Genetic testing recommended in patients with multifocal tumors,
associated paraganglioma, pheochromocytoma or family history.  SDHD gene
mutation is most common associated with familial
paraganglioma.[@davila2016; @kruger2010]

Evaluating for carotid body ligation - When involved with a CBT or other
skull base tumors, cerebral perfusion should be thoroughly evaluated
prior to surgical resection to determine whether a patient will tolerate
carotid ligation. Evaluation includes balloon occlusion testing with
xenon-enhanced SPECT imaging. Low risk for ligation if no neurologic
deficits (after 30min and hypotensive challenge) and normal diffusion of
SPECT (ratio of \>0.9).  Angiography with contralateral occlusion
evaluates collaterals.[@sugawara; @tansavatdi2015]
