---
editor_options: 
  markdown: 
    wrap: 72
---

# Venous Disease

**28 Nov 2021**: *Mr. Andrew Nickinson, Mr. Aminder Singh and Mr Manj
Gohel*

```{r echo=FALSE}

embed_audio("https://traffic.libsyn.com/audiblebleeding/Rouleaux_Club_-_Venous_Review_02auph.mp3")

```

-   Chronic lower limb venous insufficiency

    -   02:55 - What is chronic venous insufficiency?

    -   10:09 - Approach to managing superficial venous reflux

    -   20:47 - The role of surgery in superficial venous reflux
        [@brittendenRandomizedTrialComparing2014;
        @gohelLongTermResults2007; @gohelRandomizedTrialEarly2018]

    -   27:31 - What is superficial venous thrombosis?

-   Deep venous thrombosis [@kakkosEditorChoiceEuropean2021]

    -   34:38 - Screening for malignancy and thrombophilias in patients
        with DVT

    -   40:33 - The role of compression in proximal DVTs

    -   42:17 - What is post thrombotic syndrome?

    -   46:42 - The evidence for catheter directed clot burden reduction
        in proximal DVT
        [@vedanthamPharmacomechanicalCatheterDirectedThrombolysis2017]

    -   52:17 - Management of phelgmasia

-   Proximal deep venous outflow obstruction

    -   54:04 - The basics of proximal deep venous outflow obstruction

    -   57:30 - When to consider imaging the proximal deep veins in
        patients with symptoms of venous disease

    -   1:08:07 - Pelvic congestion syndrome

    -   1:11:15 - Training and service provision in venous interventions

-   Venous trauma

    -   Iliac vein injury often able to be accessed by ligating the
        internal iliac artery and mobilizing the common and external
        iliac artery. Transection of iliacs should only be used as a
        last resort if this fails. [@leeIliacVesselInjuries2002]

welcome to another podcast in our joint Bruno club, audible bleeding
series. My name is Andrew Nickenson. I'm a vascular trainee on the South
coast in the UK I'm research fellow at the university of Leicester and
also the Reno club representative for training.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* My name is Amanda Singh, and I'm
an academic clinical fellow in vascular surgery at the university of
Cambridge and a vascular specialty training in the East of England. And
I'm also the rule of club representative venous disease and the European
counselor to the European society of vascular surgery.

**andrew_nickinson-denoise:** we're going to be focusing on the topic of
venous disease over the next two parts we aim to discuss lower
extremity, superficial venous disease, proximal, deep venous thrombosis,
and complex deep venous disease. This will be \~\~an, \~\~an
$$00:01:00$$ FRCs format to aid vascular trainees with their exam
preparation for this podcast.

We're both delighted to be joined by Mr. to talk about this subject, Mr.
is a consultant vascular surgeon at Cambridge university hospital NHS
foundation trust and is honoring senior electorate and Imperial college
in London. He's also honorary secretary of the Royal society of
medicines, venous forum.

He has a special interest in venous disease. And he's well known for his
work on the landmark Ashkar and ever our studies and more recently was
co-chair of the writing committee for the European society of vascular
surgeries, venous thrombosis guidelines. Just to go, thank you for
joining us on the podcast.

**manj_gohel - denoise:** Thank you very much for inviting me guys. I've
really enjoyed the previous productions and honored to be invited and
always happy to talk about veins and venous disease. So thank you.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* ~~Yeah.~~ Thanks Mr. GoHealth. So
we'll just start off with a bit about yourself, first of all, ~~if
that's all right. Uh,~~ what sparked your interest in the management and
research of venous disease? And did you have any particular mentors that
inspired you?

**manj_gohel - denoise:** ~~Um,~~ $$00:02:00$$ so ~~yeah,~~ what a lot
of people have. So many, obviously don't realize is that you don't wake
up one day and say, I want to be a vascular surgeon. I want to be
somebody who an interest in venous disease thought about windows of
opportunity. And it's exactly the same for me. So I was very fortunate
in my sho training in Cheltonham, ~~um,~~ to have an inspirational,
~~um,~~ mentor, a consultant, the name of Keith

~~Um,~~ he spent most of his career. Researching and trying to develop
legal services. ~~Um,~~ and it was very difficult not to get caught up
with his level of passion and enthusiasm. ~~Um,~~ and so really ~~that
was the,~~ that was the beginning. I got roped into some work with the
Escar trial at that point. ~~Um,~~ and the rest is history ~~guys,~~ I
also have to mention, cause then I moved to London and, ~~uh,~~ a really
powerful mentor for me in London was Alan Davis, a professor at Imperial
college, massive venous credentials, but really provided the foundation
and platform for us ~~to,~~ to build on the earlier Venus research.

~~So, um, yeah,~~ those are two names I've mentioned, but lots of really
helpful people along the way.

**andrew_nickinson-denoise:** \~\~ brilliant. I mean, it's so common
that people go into topics because of inspiring mentors. And it's so
great to hear those too. Um, \~\~ let's go back to the basics. What is
chronic venous insufficiency and how common is it?$$00:03:00$$

**manj_gohel - denoise:** So I thought the first question was going to
be a nice, easy uncontroversial one ~~guys,~~ and you've landed in the,
~~with, uh,~~ with CVI. ~~So, so what you've,~~ what you've hit upon is
one of the main problems with venous disease, which is terminology. So
if you type in chronic venous insufficiency into Google, ~~um,~~ you end
up with, ~~um, uh,~~ this enormous range of descriptions and how you
used in lots of different ways, by lots of different people.

~~So. And~~ one of the problems is that this led to a lot of confusion
amongst people within the space let alone everywhere else. ~~So,~~ so
really important documents to guide people to is the vain term consensus
documents published in 2009. ~~I think I'm the author,~~ the lead author
was BOAC cloth. And this was a document where a whole group of Venus
experts around the world got together and said, okay, we need to be
clear and define what all these different terms mean.

And what are the terms that he found was chronic venous insufficiency.
And the official definition is it is a venous disease between C3 and C6
on the CAEP classification. We'll talk about that a bit later, I'm sure.
But between C3 and C6,$$00:04:00$$ ~~um,~~ in practice, it is used to
describe the entire spectrum of venous disease ranging from unthread
veins C1, right?

The way up to Venus alteration. But technically it is C3 to C6. And I
would urge anybody who is revising or learning about the terminology to
look at the vein term documents and silly little things like great
saphenous, vein, small saphenous vein. ~~Um,~~ I think UK is the only
place where long sadness is ever used.

~~Um,~~ and the real problem was LSV and lots of other countries will be
the lesser saphenous bean, which is the small saphenous vein. So again,
~~um, you know,~~ I'd urge anyone to look at that document. ~~Um,~~ how
common is it very common? \~\~Um, you know, and if you, if you sort of,
you know, hopefully \~\~with the weather getting a bit nicer, ~~you, you
know,~~ people wearing shorts, you're spotting, venous disease, ~~you
know,~~ all over the place.

\~\~Um, \~\~ the studies that have been done indicate that at least a
quarter, probably up to a third of people have C2 to C6 disease. So very
common problem, lots of people that need treatment.

**andrew_nickinson-denoise:** that takes us on quite nicely to ask about
the cash of and scoring systems. You mentioned CAEP ~~um,~~ could you
expand on that?$$00:05:00$$

**manj_gohel - denoise:** Yeah, of course. \~\~So, um, again, really,
\~\~really important. So seek the critical ecological with an E because
it's American anatomical pathophysiological classification system was
introduced, I think in the mid 1990s, again, by, ~~uh,~~ the American,
~~uh,~~ venous forum and American colleagues. And it's a classification
system.

So if you have a patient that comes into your clinic with a venous
problem, it's a system to allow you to describe that patient's current
situation in a very objective, very clear way, what it does not do it
give you any information about prognostication and what it doesn't do,
but it isn't useful for is measuring responses to treatment.

So it is purely a descriptive classification system. ~~Um,~~ so that
seat, ~~um,~~ and the most commonly used bit is the clinical bit, which
is C1 one to C6. And again, CAEP was just recently revived last year, a
25 year revision, which again, I would urge trainees to have a look at,
~~um,~~ federal Lurie was the lead author, ~~um,~~ and just some
useful\~\~ , uh,\~\~ revisions of $$00:06:00$$ CAEP.

\~\~Um, \~\~now in response to the limitations of CAEP. \~\~Um, ~~again,
there was a new~~ , uh,\~\~ clinical\~\~ , um,\~\~ scoring system that
was created, which was a VCSs of Venus clinical severity score. So this
is a 10 item scoring system, each item scores between zero and three. So
you get a maximum score of 30. Now this is designed to be responsive to
treatment.

And so it's designed to be complimentary to CAEP. \~\~Um, \~\~there are
lots of other things that have been described, quality of life tools,
DBS, lots of other things. I would say that those two are the most
relevant and important ones to know about. \~\~Um, \~\~ but again, the
number of papers I've reviewed where people have\~\~ , um,\~\~ reported
CAEP scores as one of the outcome measures in response to treatments.

That is not what it's designed for. \~\~I mean, \~\~for example, you can
never get lower than C5. You can never get better than a healed ulcer.
\~\~So, um, \~\~so again, that's the important distinction.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* when we do see patients in clinic
with chronic venous insufficiency, which type of imaging modalities
should we use to investigate the function and the anatomy of the lower
limbs?

**manj_gohel - denoise:** ~~Um, so really important question, Amanda.
Um, so~~ if a patient comes to clinic, we can't $$00:07:00$$
underestimate the importance of the clinical assessment. And when you
assess these patients, you really looking for two things, you are
looking for the impact of their venous disease on their quality of life
and the impact of the venous disease has on their normal function.

But also you're looking for complications of venous disease. This is a
clinical assessment. Again, what's your question about the
investigations? \~\~Um, \~\~You really want to identify underlying
treatable causes of their venous disease. And \~\~that's the, \~\~that's
the goal of any investigation. \~\~Um, \~\~and being the stoop legs.

Imaging is obviously the first line gold standard that pretty much
anybody \~\~will, ~~will go to around the world. And what that does is
essentially gives you information about the flow, both~~ , uh,\~\~ in
the normal antegrade, but also retrograde or refluxing a flow in
superficial and deep veins. \~\~Um, \~\~it'll gives you information
about the anatomy of the beans, which will help you to plan treatment,
but it also gives you lots of other information as well.

It gives you information about\~\~ , uh,\~\~ in the common femoral vein.
For example, if there's good phase, this city $$00:08:00$$ of flow, if
there's no scarring, it helps you to evaluate whether there might be
some outflow obstruction. \~\~Um, \~\~so duplex imaging is the absolute
first line gold standards. Now, once you've done the triplex imaging, if
there's clinical suspicion.

Then of course we can move on to other investigations. So proximal\~\~ ,
um,\~\~ CTV, MRV, venography IBAs, all sorts of other weird and
wonderful things. But clinical assessments and duplex assessment are the
bedrock of every\~\~ , uh,\~\~ assessment of every Venus patient. So
that's the foundation.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* so you mentioned\~\~ , uh,\~\~
quality of life. A couple of times then is to go hell, we might as well
discuss that a bit further \~\~in this, \~\~in this section. Clearly the
spectrum of venous disease can impact a patient's quality of life, quite
significantly. What tools and methods do we have to be able to assess
the impact on a patient's quality of life?

**manj_gohel - denoise:** \~\~So, \~\~so in a research setting, \~\~I
mean, there's, \~\~there's many validated questionnaires. \~\~Um,
\~\~but anyone involved in seeing these people and doing the
evaluations, know how cumbersome they are. \~\~I mean, \~\~you can't sit
with a patient for 20 minutes and then $$00:09:00$$ NHS clinic and go
through. An AB VQ or a veins call SIM questionnaire as much as you'd
like to.

\~\~Um, \~\~so there are validated tools available. \~\~Um, \~\~I
suppose what we really need. And again, if somebody wants to, \~\~okay,
I was going to say, make a million, but you're not going to make a
million out of this. But if somebody wants to have a, you know, \~\~get
their name on a few papers, \~\~then ~~then a practical~~ , um,\~\~ easy
to use clinical tool that is validated for assessment of patient
reported outcomes is what we need.

\~\~Um, and, \~\~and I think that the important thing here is that the
tendency for vascular specialists and Venus specialists is to focus on
the imaging, then treat a lesion or treat a refluxing vein, or treat us
the gnosis. We've got to get away from that. We're treating patients and
~~you know, you,~~ there's no point treating the stenosis and say
symptomatic.

There's no point treating a lesion is not. Going to make a difference to
the patient. So \~\~that \~\~that clinical correlation is absolutely
imperative. So it's really just to teach the mindset, \~\~you know,
\~\~always ask patients, how much does it impact you on a daily basis?
What is it that your Venus disease stops you from doing?

\~\~Um, \~\~so those are the sort of questions I think we should all
ask.

**andrew_nickinson-denoise:** Yeah. \~\~I mean, \~\~that's, such an
important point. And I know as a $$00:10:00$$ speaking person who is a
trainee, we will tend to focus on what we see in front of us and the
disease rather than how it affects the patient. And that's a really
excellent point moving on to the treatment of superficial disease. ~~Um,
I think we're going to go slightly off, off what I've written here, but
, um, when we talk about,~~ when we talk about treatment of superficial,
Venus and competence, I don't think we can really get away from talking
about the two major studies.

The Ashkar in there for our studies, which I know you've been involved
with. Mr. Girl, would you mind just \~\~sort of \~\~talking briefly
about \~\~what, ~~what these~~ , um,\~\~ studies showed and their
importance \~\~of , uh, \~\~in the care of our patients.

**manj_gohel - denoise:** Yes, of course. \~\~So, \~\~so \~\~just,
~~just before I go into the trials~~ , um,\~\~ I'm just going to go back
a step and just talk about the general mindset that's important for
these patients. ~~So th~~ so what we're treating with these patients is
not superficial venous reflux. What we're treating is chronic venous
hypertension.

So we're treating \~\~a, \~\~a global pathophysiological entity of which
the superficial reflux is one correctable factor. And the reason that's
important is that there may be other correctable factors, \~\~you know,
~~venous, outflow, obstruction~~ , um, \~\~other sort of mobility
related things that \~\~they can, \~\~they can $$00:11:00$$ adjust.

But they're also going to be lots of. Uncorrectable factors\~\~ ,
um,\~\~ poor mobility\~\~ , um,\~\~ heart failure, dependency, ankle
stiffness. If your ankle is stiff, you can't use your calf muscle pump
effectively. You don't have that mechanism for clearing the pressure out
of your legs. \~\~So, \~\~so these treatments, the success of these
treatments, particularly for the ulcer population has to be taken in the
context of treating venous hypertension as well.

Having said that the aim of these trials was to put together was really
very simple. ~~In~~ most patients with venous ulceration have got
superficial reflux. So what is the role of treating the superficial
reflux? ~~But those~~ that's the simple question that was asked by these
trials. So the Escar trial recruited between 1999 and 2002, 500 patients
with healed and open.

And they either were under most of compression or compression and ~~kind
of~~ traditional, superficial venous surgery, stripping or ligation if
they were on it. And that trial was very clear. It showed that there
wasn't a benefit for healing, $$00:12:00$$ but there was a significance
and, \~\~you know, \~\~really sizeable reduction in the risk of Elsa
recurrence.

If you treat the superficial reflux with stripping, so really important
findings\~\~ , um, the Everest study.\~\~ So one of the criticisms of
that scar was lots of people didn't have their surgery. Lots of people
had just ligation alone, et cetera. We don't really do stripping
anymore. It's endo Venus. So ~~Escar really aimed to bring~~ everyone
really, to bring the Escar trial up to modern practice.

And we randomized hundred and 50 patients with open leg ulcers to end
the Venus treatments early delivered ~~with two~~ within two weeks
versus a more delayed approach and whatever showed again, \~\~you know,
\~\~common sense if you do with the underlying problem, the venous
ulceration healed significantly quicker.

So put them together clear unequivocal argument for treating the
superficial reflux in these patients as quickly as possible.

**andrew_nickinson-denoise:** Can you broadly outline the \~\~different,
\~\~different treatment options that are available to, or can be offered
to patients with superficial Phoenix reflex?$$00:13:00$$

**manj_gohel - denoise:** Yeah. \~\~So, so, uh, \~\~another presentation
I've given recently has looked at different treatment options, and I
have counted about 42 different ways of motoring, a saphenous vein.
\~\~Um, so, \~\~so ~~I'm gonna,~~ I'm going to actually be slightly
obstructive and not answer the question. ~~Um, so~~ there are lots of
different treatment options.

What is \~\~much, ~~much, much more important is doing it quickly. And
getting it done rather than which hot Zack are you going to use~~ ,
um,\~\~ do something that you're trained through, something that's
appropriate. I\~\~ I mean, \~\~thermal ablation has in the nice guidance
and in lots of other international guideline documents has been
combined, whether it's radiofrequency or laser.

\~\~Um, and, \~\~and I think even folks near a therapy, which has got in
the randomized studies, lower technical success rates, lower vein
closure rates in the leg ulcer trials, the clinical success rates in
terms of also healing are just as good. \~\~So, you know, this, \~\~this
sort of five, six, even 10% reduction in closing the vein, doesn't
really seem to translate into a significant drop in clinical
effectiveness.

So I think the most important thing is not $$00:14:00$$ necessarily what
you use, it's doing it quickly and delivering it to the people that need
it.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* so when we are consenting patients
for endovenous intervention, what risks should we discuss with the
patient and that they need to be aware of?

**manj_gohel - denoise:** \~\~um, \~\~ so you can spend an hour doing
this \~\~if you, ~~if you're being very diligent about it with the
recent sort of legal rulings in the UK, et cetera. But what I say to
patients are that there are generic risks of venous thromboembolism is
the risk of any intervention. And I think that's worthy of specific
discussion in a little while after under beans procedures, but I quote a
risk of around one in 200~~ , uh,\~\~ for most intervenous
interventions.

\~\~Um, \~\~there's always a risk of bruising. And if you didn't,
phlebectomies what I often tell people is that bruising sometimes looks
worse than it feels. \~\~Um, ~~and with the third one interventions in
particular~~ , um,\~\~ I think the risk of. Nerve related complications.
So some numbness or some nerve pain are worthy of mentioned, and of
course the risk of recurrence.

So these are the main things to mention. Now, a couple of specific
things. ~~So~~ foam sclerotherapy\~\~ , um, has got some , uh,\~\~
obviously a different mechanism of action. \~\~It's a, \~\~it's a
detergent that's injected into the $$00:15:00$$ vein that kills the
endothelium. And there are some people that have associated foam sort of
therapy with some neurological events.

\~\~Um, ~~so the very large registry~~ , um,\~\~ that was organized by
the manufacturers of fiber vein recently looked at 10,000 patients in
the UK. \~\~Very \~\~very few events. So handful events and event rates
of around one in four, one in 5,000. \~\~Um, \~\~and some people say
that who've got a history of migraine, then the risk of these
neurological events might be a little bit higher.

\~\~So, \~\~so again, a little bit of caution, although in practice,
I've treated many people with migraines. \~\~Um, you know, \~\~if you
believe the literature, \~\~one in sort of, you know, \~\~one in four or
five, people have got a little ASD and, \~\~you know, \~\~obviously we
treated lots of those people, so the risks are \~\~very, \~\~very low.

\~\~Um, \~\~but it's just important to have that discussion beforehand.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* are there any techniques that we
can use to mitigate some of these risks?

**manj_gohel - denoise:** Okay. So I think VT is something that is
really worth specifically discussing. \~\~So, um, \~\~it's a very rare
event after superficial venous interventions, but it's potentially
catastrophic. It's \~\~sort of, you know, \~\~newspaper worthy. If
\~\~you know, ~~young people~~ , um,\~\~ end up having a very bad
outcome and $$00:16:00$$ we've seen headlines and ~~poor~~ colleagues
that have been dragged through the mud over this.

And I think what we've got to realize is that, although \~\~the rate,
~~the rate of these~~ , uh,\~\~ VTE events is \~\~very, \~\~very low.
There are almost certainly some people that have got a higher risk. And
so what we've got to get slightly smarter about is identifying the
people that put a higher risk of VTE. And maybe giving them \~\~a, \~\~a
prolonged course of thromboprophylaxis as well as appropriate counseling
and mitigation as well.

So it's about getting smarter about risk assessment. The kind of risk
assessment tools are not really fit for purpose when it comes to
superficial venous intervention. So the department of health where the
Caprini tools don't really take into account some of the really
important factors that I think do impact on VT risk after superficial
venous interventions.

\~\~Um, \~\~so again, ~~what we have, so if~~ there's nothing validated,
there's nothing widely available. \~\~Um, ~~Isaac name meet she's a
vascular surgeon and Worcester has done a lot of work on this over many
years, but what we have in Cambridge is a~~ , uh,\~\~ local\~\~ , um,
~~specific risk assessment approach~~ $$00:17:00$$ to , uh,\~\~ patients
having superficial venous interventions.

There are major risk factors we look out for, which has specifically
things like previous ipsilateral VTE, active malignancy, but also
significant chronic inflammatory conditions. There's somebody who's got
inflammatory bowel disease. Actually, these patients have a much higher
risk of VTE that we previously recognized.

\~\~Um, \~\~and they're also minor factors, of course, superficial vein
thrombosis, obesity co-morbidities \~\~um, ~~so all of these things then
get put together. We come out with a school and then for patients above
a certain threshold, they get offered extended~~ , uh,\~\~ rivaroxaban
all over like the, it happened. \~\~Um, \~\~so then we can get smarter.

\~\~Um, \~\~and also mitigation. \~\~I mean, uh, \~\~so traditionally
things like lapel and HRT and Tamoxifen, \~\~you know, \~\~we've not
stopped them \~\~traditionally \~\~because it's, \~\~you know, \~\~it's
just a local anesthetic procedure, \~\~you know, \~\~why do we need to
stop them? ~~And I think it's, it's an ease. So I haven't~~ been on an
estrogen containing\~\~ , um,\~\~ pale doubles or trebles your risk of
ETA.

So it's an easily reversible thing in the short term \~\~that can be,
\~\~that can be done. So for my patients, I would normally recommend
that we do that. So we stop it, \~\~you know, ~~full cycle~~ , uh,\~\~
$$00:18:00$$ before for the pill. \~\~Um, \~\~and similarly a month
before and after penny Johnson,

\*\*aminder-2021-4-18\_\_17-8-43:\*\* you mentioned it an extended
course of anticoagulation for those patients with risk factors, ~~Mr.
Goldhill,~~ is there a specific timescale locally that you use for this.

**manj_gohel - denoise:** \~\~So, uh, again, so the, \~\~ the venous
forum\~\~ , um,\~\~ actually produced\~\~ , um,\~\~ some guidance
\~\~last year to help actually even \~\~the year before last ~~now sort
of erase the whole of last year from my memory, unfortunately. So, um,
so produce some guidance , um,~~ in exactly this area. \~\~Um, ~~and we
use about a week or 10 days~~ , uh,\~\~ for a lot of these patients, but
if there's a, if there's an ongoing, persistent risk factor, then
actually the VT risk persists for four to six weeks, which is an
argument for up to six weeks to carry on for particularly high risk
patients.

I think if at that high risk, you've really got to question whether a
superficial venous intervention is needed\~\~ , um,\~\~ balancing the
risks and the benefits. \~\~Um, \~\~but it is interesting. So after
these procedures, we know that the VTE risk ~~proceeds~~ is there for at
least another six weeks afterwards. \~\~So, \~\~so for the really high
risk patients, don't stop it too soon.

**andrew_nickinson-denoise:** ~~Um, okay. Uh, so~~ moving on to a
specific question about treatment, ~~but~~ what is the role for treating
and competent perforator veins in these patients?

**manj_gohel - denoise:** So the facetious answer is $$00:19:00$$ it
depends on how much you're being reimbursed for them. But \~\~the, ~~the
clinical answer is~~ , um,\~\~ relatively little ~~in,~~ in my practice
and ~~in,~~ in most sensible practices. ~~Um, so, so look, if we scan,
so~~ the more advanced the venous disease, the more likely you are for
the disease to be recurrent, the more likely there is to be deep venous
disease or posts from the disease.

And the more likely you are to finding competent perforators. So the
more advanced the venous disease, all of these things are more likely.
So ~~if you manage these,~~ if you imagine these patients with being ,
it is very common to find perforators. \~\~Um, ~~and if you take a sort
of super aggressive role saying you've got to obliterate every single
bit of reflux you can find~~ , well,\~\~ then you'd be doing a couple of
perforators and every single patient.

\~\~Um, \~\~and that is the approach of a number of centers around the
world. \~\~Um, \~\~the pragmatic reality is number one, if you ablate
the superficial reflux, we know that a lot of these perforators actually
become competent because we've got rid of the outflow or you've changed
the dynamics in some other way. And they've become
competent.$$00:20:00$$

Even if they've stayed in competence, the clinical benefit is still
there and is usually still pretty durable. Now, of course, there may be
some people that develop recurrent problems and then there can be a more
targeted approach to the perforator. ~~So I personally, and~~ the ESCO
and Everest studies did not target perforators at all.

And the outcomes in the Everest study was the best healing rate of any
published prospective Lego study. \~\~So, \~\~so putting all that
together, it's difficult to make a case for aggressive treatment of
perforators first up. \~\~Um, \~\~having said that for some people with
recurrent disease, it's not uncommon to have a big mid thigh Ontarian
perforator, or, \~\~you know, \~\~big cockpits perforated, lower Pronto
down on the medial side.

\~\~So, uh, you know, \~\~I do treat perforators, but almost always it's
in recurrent disease with recurrence or deteriorating symptoms.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* so we've discussed quite a bit
about endo venous intervention. \~\~Um, \~\~is there a rule for open
surgery in some patients?

**manj_gohel - denoise:** ~~So~~ interesting. ~~So~~ open surgery
remains the most commonly used superficial venous intervention around
the world. And there are still lots of centers in the UK that
$$00:21:00$$ primarily offer open surgery\~\~ , um,\~\~ and\~\~ ,
um,\~\~ being balanced. It's a very effective treatments if you do it
well, if you use\~\~ , uh,\~\~ modern approaches tumescent anesthesia
ultrasound guidance, then actually some of the traditional issues with
open surgery, which are often technical and complication related, don't
really apply.

Having said that all the randomized trials have shown the same thing
while the effectiveness may be as good in open surgery done well, the
recovery is much better after intravenous ablation. So it's difficult to
make the case for open surgery when you've got something that is so
well-established and the competition was just so low.

And it's cheaper when you look at their theater capacity, et cetera.
\~\~So, \~\~so \~\~I think, \~\~I think there has to be a steady drift
towards endovenous, but there are lots of things stopping this. \~\~I
mean, \~\~in Germany, for example, the reimbursement is greatest rope
and surgery. So surprise, surprise. There are still lots and lots of
open varicose vein operations.

And again, for you guys, if you're going to change practice, the single
biggest $$00:22:00$$ driver for change in practice is reimbursement.
\~\~Um, \~\~you know, if you can, you can change where the money goes.
You can change whatever you like. \~\~Um, so, you know, \~\~and the
final thing is \~\~I've, \~\~I've treated maybe three in the last five
years.

I've three patients with open surgery. One was a GP who I had treated
the other leg with open surgery a few years earlier, and she said, I
want the same operation, please. So I did struggle to argue with that.
The other two were big saffron, the viruses in the groin, \~\~you know,
\~\~three, four, five centimeters suffered at mercy.

So specific indications. But not really for most patients,

**andrew_nickinson-denoise:** I suppose that comes on to training as
well the UK. If Australia's, aren't doing as much open surgery, then,
\~\~you know, ~~conceivably over time that we're going to lose those
skills of being able to do~~ , uh, \~\~sadness, cutdown or stripping.

**manj_gohel - denoise:** \~\~it's such a shame, Andrew, \~\~it's such a
shame. \~\~It's, \~\~it's the operation that I learned how to operate
with. \~\~You know, it's, it's, it's, \~\~it's a beautiful anatomical
operation. \~\~Um, \~\~and you learn so much, \~\~you know, \~\~respect
for tissues and handling blood vessels. And it's great preparation.
\~\~So, \~\~so it's with a heavy heart that I'm \~\~sort \~\~telling
trainees that, \~\~you know, \~\~you shouldn't be doing this cause it's
such a great training operation.

**andrew_nickinson-denoise:** \~\~Um, \~\~ so we've talked about
$$00:23:00$$ intravenous and surgical treatment. \~\~Um, ~~but are there
any pharmacological therapies that can be used~~ , um,\~\~ in patients
with chronic venous insufficiency?

**manj_gohel - denoise:** ~~We are , um,~~ we're pretty skeptical in the
UK. \~\~Um, ~~when it comes to Vino active or pharmacological
treatments~~ , uh,\~\~ if you go to Europe\~\~ , um, \~\~they love them.
\~\~They, \~\~they sell like hot cakes. They're over the counter in a
lot of pharmacies. \~\~Um, \~\~and it's interesting. So \~\~the, ~~the
drug with probably the most evidence is something called Naflon~~ ,
um,\~\~ law and micronized purified flavonoid fraction.

So flavonoids on naturally occurring\~\~ , um,\~\~ Vino active
compounds. Are there a whole variety of, because effects\~\~ , um,\~\~
only some of which we understand, but a lot of studies have shown
improvements in Adima improvement in heaviness. \~\~Um, \~\~and Def lawn
is marketed by a French company and it's got good evidence, but they do
not see places like the UK as a big enough market because of our
inherent skepticism over these sort of things.

To make it worth their while to go through the\~\~ , um,\~\~ the
marketing and the regulatory stuff. So it's not available. \~\~So, um,
~~but patients that have~~ $$00:24:00$$ gone to France and picked it up
over the counter , um,\~\~ have said it works well. So there may be a
rolling and pen toxifying and these other things. So that there's some
good evidence \~\~that, \~\~that accelerates healing of leg ulcers.

\~\~Um, \~\~I don't think we're very receptive in the UK in general. So
not in the vascular surgery community ~~to , um,~~ to be \~\~sort of
\~\~pharmacological or herbal time remedies.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* nice recommends that we should
undertake\~\~ , uh,\~\~ treatment for varicose veins to improve a
patient's quality of life. But currently within the NHS and not all\~\~
, uh,\~\~ CCGs will actually fund this.

What's your views on this particular subject?

**manj_gohel - denoise:** \~\~So, um, \~\~ I'll try and answer the
question without swearing. ~~Um, it it's, it , uh,~~ over the years I've
had so many frustrating interactions with CCGs. ~~Um, so~~ the
commissioners that fund varicose vein treatment, ~~so~~ the whole point
of nice is to give centralized guidance. So there can be some
consistency of care and provision across the country.

\~\~Um, \~\~but again, the problem is with the funding and the CCGs hold
the budgets and they have differing rules and in general, There has been
a tendency over many years to try and resist $$00:25:00$$ funding,
varicose vein treatments. \~\~Um, ~~so my view is that CCGs should
follow the nice guidance~~ , uh,\~\~ and a lot of these patients should
be offered treatment.

\~\~Um, ~~the other comments I'd make is that even the CCGs are, do
offer treatment~~ , um,\~\~ there is still \~\~a, \~\~a big ~~missing,~~
missing piece, which is \~\~the, \~\~the treatment mindset and the
pathway. So it's no good having a document that says, yes, if you have a
venous leg ulcer, you can have varicose vein treatment. If the pathways
don't encourage referral, if the education level of the primary care
nurses and the GPS isn't there.

\~\~Um, \~\~if \~\~the, \~\~the hospital is providing the treatments,
provides a resistance to seeing and assessing these patients and all of
these things are happening across the country. \~\~So, um, \~\~I think,
\~\~you know, you, ~~you look at arterial disease~~ , um,\~\~ and.
There's so much controversy over a lot of the treatments that we're
providing.

\~\~You know, \~\~you look at \~\~the, the, \~\~the debate and the
challenge of aortic aneurism treatments recently, et cetera. \~\~I mean,
\~\~the treatment of Erika Spain disease is unquestionable indisputed
\~\~it was it's \~\~it's clearly evidence-based, it's low hanging fruit.
~~It~~ not only is it cost $$00:26:00$$ effective, it saves money. So
it's very frustrating that there's not more pathways.

And I think \~\~this is, \~\~this is part of \~\~the, ~~the ongoing work
that we all have to do both people at your level, but also obviously
enthusiasts like me and other advocates to try and just keep the message
going and keep it going then. And final, quick comment I'd make is about
COVID and~~ , um,\~\~ the associated challenges to funding.

\~\~Um, \~\~so at the moment there's a bit of a blank check approach to
healthcare. It's not going to last ~~guys, it's going to,~~ there's
going to be a time when ~~some~~ somebody in government says, okay, so
we need to now start trying to balance the books. I can already tell you
now that one of the first things that's going to get attacked is
superficial venous treatments and varicose veins.

\~\~So, \~\~so we've just got to get our arguments ready and be prepared
for this ongoing battle that's been there for as long as I've been
adopted.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* What are the healthcare costs
associated with the lower extremity venous disease?

**manj_gohel - denoise:** \~\~um, \~\~honest answers. We don't know.
\~\~Um, \~\~there have been a number of studies that have looked at
venous ulceration and the impact of $$00:27:00$$ venous ulceration, and
there's \~\~sort of \~\~guesstimates that people have put together
educated guesstimates in the UK. NHS is around 2 billion pounds a year.
So UK NHS, budget's about a hundred, 120 billion.

\~\~So, you know, \~\~up to about 2% of the budget, \~\~you know, big
bucks, \~\~big bucks, and that's just C6 disease. ~~You know, we
haven't,~~ we're not even going into all of the other diseases, the
associated cellulitis, but also not only the healthcare costs, but the
societal costs, \~\~you know, \~\~the time off work, the other things.

And then of course the superficial vein thrombosis and the VTE and
August other associates, it's a massive underestimate

**andrew_nickinson-denoise:** you mentioned superficial vein thrombosis.
They're also known as superficial thrombophlebitis. \~\~Um, \~\~just a
few words on it. What is it and how do you manage it?

**manj_gohel - denoise:** I'm very easy to use both terms because I'm
going to take the opportunity to encourage robustly the use of
superficial vein thrombosis rather than thrombophlebitis. The problem
with thrombophlebitis is it is too closely associated with an effective
etiology and effective pathology. And I can only imagine how
$$00:28:00$$ many useless courses of antibiotics have been prescribed.

For the treatment of what has been presumed to be an infected properly.
Of course, there's no infection, \~\~it's a, \~\~it's a thrombus in the
superficial vein. \~\~Um, \~\~and I think what's really important is
that traditionally it's been seen as just a bit of a nuisance and let's
not worry about it and, \~\~you know, \~\~analgesia and
anti-inflammatories, and you'll be fine.

\~\~Um, \~\~it's a \~\~really, \~\~really sinister pathology. It's an
important cause of VTE. \~\~And, \~\~and again, if you think about it,
think of how many thousands, millions of people that are with varicose
veins. \~\~Um, \~\~they don't all get clots in their varicose veins.
~~You know, this is these people,~~ they've all got stasis to a certain
extent.

They don't get clots. So ~~it's~~ more than just the flow dynamics is
going on here. These people are thrombogenic. They have a thrombogenic
innate quality that leads to this\~\~ , um,\~\~ and that's shown out in
the study. \~\~So, um, ~~some really good work in some French studies~~
, um,\~\~ where they identified patients who were scanned with
superficial vein thrombosis, And a quarter of them on their first duplex
scan had a DVT, so supervision for most of the quarterly
DVT.$$00:29:00$$

And a lot of these DBTs were remotes from superficial vein thrombosis.
So they're all extending into the deep vein they were remote. And again,
\~\~you know, \~\~confirming this idea that actually a thrombogenic
problem is going on here. ~~Um, and so what we~~ send the latest CSPs
guidelines, there is quite a lot of stuff about SVT treatment
algorithms.

And again, I would urge people to have a look at that, and it's
important to risk stratify people. The closer you are to the junction,
the higher VTE risk, and actually for anyone other than just a bit of
clotting of Erik hostility, anticoagulation is the treatment of choice
to reduce progression to BTU.

So again, I won't go into lots and lots of detail, but look at the
guidelines. It's very clear what we should be doing with these people.
Evidence-based and then once the anticoagulation is done, They needs to
be rescanned and that residual incompetent, scarred thrombogenic\~\~ ,
uh,\~\~ Safa Spain needs to be ablated.

Otherwise they'll recur. So a real change in mindset and level of
$$00:30:00$$ aggression.

**andrew_nickinson-denoise:** ~~Right. So, um, So in terms of questions,
we've sort of exhausted our, what we'd already written about superficial
venous disease. I suppose the question now is, do we talk, do we move on
to talk about deep venous thrombosis? Um, it depends on timing for
yourself, Mr. Goa.~~

**manj_gohel - denoise:** ~~so I'm, I'm happy to guys, I'm happy to just
carry on. Um, and, and then I'll leave it to you guys to work out what
you want to do. Um, whether you want to do a sort of a best of both and
combining it into one, or whether the split to, I mean, I'll leave that
honestly, up to you guys. Um, I don't, I don't, I don't want to be too
greedy and have two different sort of.~~

~~Things just with me talking, but I'll be, I'll be guided by you.
Whatever's going to be most useful.~~

\*\*aminder-2021-4-18\_\_17-8-43:\*\* ~~Yeah, I think the thing that
feeling is probably two podcasts would be the best way to do this. Um,
do you think we should talk about bleeding, varicose veins as well as
part of this,~~

~~because it's something which you do see, I think this is something
which we do see , uh, and it's just maybe putting a bit of
evidence-based behind how we should be treating that.~~

**manj_gohel - denoise:** ~~Yeah, absolutely. Um, so ask me a question,
Amanda.~~

\*\*aminder-2021-4-18\_\_17-8-43:\*\* ~~yeah.~~ What's your approach to
managing patients with bleeding, varicose veins, Mr. Google.

**manj_gohel - denoise:** Really important question. It is a vascular
emergency. ~~Um, so~~ there are several depressing reports of patients
having died from bleeding, from a very costly and is often elderly
patients who are frail, who have arthritis in their hips. And therefore
can't bend down to press on\~\~ , um,\~\~ the bleeding are costly down
by the ankle and also.

\~\~Um, ~~and actually there's some very~~ , um,\~\~ grim photos\~\~ ,
um,\~\~ in various case reports and\~\~ it's , um, ~~it's really sad.
There's two or three photos that I've seen where an elderly~~ , um,
\~\~patient has not wanted to wake their partner. \~\~Um, \~\~and so has
gone and laid down in the bath with this bleeding vein that they
couldn't control and basically exsanguinated.

\~\~Um, \~\~so \~\~it's a, \~\~it's a vascular emergency. \~\~Um,
\~\~and these patients should be seen and assessed and the superficial
venous disease should be dealt with as soon as possible. Ideally, when
they're assessed as an emergency. \~\~And as you know, \~\~ we had an
emergency clinic running throughout COVID ~~in there.~~ And anyone with
bleeding veins have the $$00:31:00$$ same urgency as the CLI patients.

\~\~Um, ~~and they were treated there. And then~~ , uh,\~\~ in terms of
the treatment, there's two aspects. So you want to decompress ~~the ,
um,~~ the venous hypertension by ablating, the saphenous reflux, but the
specific bleeding area. I think there's a real case for some local foam
sclerotherapy. \~\~Um, ~~you want to block off that vulnerable bleeding
vein~~ , um,\~\~ and to ensure that this doesn't happen again\~\~ ,
but,\~\~ but again, \~\~you know, ~~if anyone receives a referral~~ ,
um,\~\~ these are \~\~sort of \~\~people to see straight away.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* So let's move on to discuss deep
venous thrombosis. You're recently involved \~\~in the , uh, \~\~in the
European society of vascular surgery, venous thrombosis guidelines,
~~Mr. GoHealth , um,~~ in the most part, cough DBTs are managed by
medical teams or dedicated DVT services within the hospital. So in this
section, we'll be focusing mostly on proximal DVT in medical school.

We've learned a lot about varicose triad and the etiology of venous
thrombosis. Does that simple concept still hold true today.

**manj_gohel - denoise:** \~\~um, \~\~ I think it does. \~\~Um,
\~\~okay. There's a few caveats and a few nuances, but I think the
principle that the flow, the vessel $$00:32:00$$ wall, the blood
constituents are the main factors that affect whether or not you get
thrombosis \~\~in, in a, \~\~in a vein is still pretty solid. ~~Um, of
course it's much more nuanced than the again.~~

\~\~So you, you, \~\~ you kindly gave me a lot of credit for these
guidelines. It was as a massive team efforts, and it's great to have
experts from around Europe, multidisciplinary experts. You've got to
realize that a lot of vascular surgeons aren't really that involved with
DVT management. So having, \~\~you know, \~\~professors of hematology
and internal medicine, \~\~it was, it was, you know, \~\~It was feisty.

\~\~Um, \~\~but it was \~\~very, you know, \~\~really good experience.
\~\~Um, \~\~so yeah, burqas tried \~\~very, ~~very valid~~ , but,\~\~
but also real changes in mindset about the whole idea of provoked and
unprovoked DVT\~\~ , um, which , uh, we may come on to, but I think
\~\~again, I would urge people \~\~to, \~\~to look at some of the new
areas that we've covered in these guidelines.

**andrew_nickinson-denoise:** You mentioned there about\~\~ , um,\~\~
potential risk factors for DVT, and that can be classified into these
provoked, which can be transient or persistent and then unprovoked risk
factors. Can you talk about some of the specific factors and causes

**manj_gohel - denoise:** \~\~Yeah, of course. So, um, \~\~in general,
what's been happening for several years \~\~is, \~\~is a $$00:33:00$$
recognition that there are some DVCS that happened with a clear
provoking factor. \~\~So, you know, \~\~the communist major. Transient
provoking fats with something like surgery, for example. So a lot of DVT
is, are called, \~\~you know, ~~with that clear provoking factor, but
there's an enormous population of people that don't have a clear
provoking planter at all, or have this sort of~~ , um, \~\~minor factor
that may or may not have contributed.

\~\~Um, and, and what we've. \~\~So traditionally there's been a
dichotomy between provoked and unprovoked. If it's provoked, they get a
limited period of anticoagulation is unprovoked it's long-term, ~~that's
been the dichotomous station.~~ And certainly the last big thrombosis
guidelines was the ACP guidelines, the American chest guidelines, and
that's what they suggested.

\~\~Um, \~\~but it's much more nuanced than that. And what we've got to
remember is that there are some provoked DBTs where there's much higher
risk, and those are there's some unprovoked DBTs, which actually there
may be other factors that you need to take into account. So I think for
those people that are interested in this area, it's really important
\~\~to, \~\~to get to the nitty gritty.

So $$00:34:00$$ long-winded way of answering your question. Major
provokes would be surgery, major trauma, but minor provoked are those
sorts of minor bits of immobility. \~\~You know, \~\~if you've been in
bed for a couple of days with flu, but is that a provoking pattern or
not? We don't really know things like being on the contraceptive pill.

So yes, if you've only just started it, that would be considered a
provoking factor, but there are some people that have been on the pill
for two or three years and then get a DBT. Can we really say that's a
provoking factor? \~\~So, \~\~and again, a guideline document is a big,
long list of other things where for people to think about it and
consider.

**andrew_nickinson-denoise:** and in those patients where after you've
taken a thorough history, \~\~there \~\~there's no obvious provoking
factors. Is there a role for screening for occult malignancies and
thrombophilias.

**manj_gohel - denoise:** ~~um, so~~ there was a big trend. \~\~So,
\~\~so thrombophilia testing the history of it's really interesting.
~~So~~ when they were first identified and our ability to screen them
first became available\~\~ , um,\~\~ there's a lot of excitement because
people thought, yes, we're going to be able to identify a clear cause
for all of these unprovoked $$00:35:00$$ DBTs.

And the reality is at least 50% of them, there's no identifiable
thrombophilia. So what it almost suddenly means is there's lots of
thrombophilias that we haven't yet identified we can't test for. \~\~Um,
\~\~so it hasn't really been the panacea in that regard. \~\~Um, \~\~and
the other pragmatic reality for the thrombophilias is that if we're
going to be putting people on long-term anticoagulation anyway, the
additional value of testing for these things is really very minimal.

And the ones that are really important. No, the homozygous, the
antithrombin, the homozygous rectify me. The thrombosis history is so
stark that they normally smack you in the face. \~\~So, \~\~so I think
it's generally gone out of fashion. And again, there's only very
specific circumstances where we would suggest testing them.

If you're going to be trying to stop anticoagulation. For some reason,
\~\~you know, ~~patients don't want to be on it, or if there's bleeding
risks or other things, then there might be an argument there for some
sort of risk stratification, but also there's a clear family history.
And then it might~~ then be what I think would \~\~be worth excluding
some of the more sinister thrombophilias, but otherwise, $$00:36:00$$
certainly not a role for routine testing \~\~and, \~\~and similarly for
malignancy.

\~\~Um, \~\~so unprovoked DVT, the prevalence of an underlying
malignancy that studies have been done between six and 10%. \~\~Um,
\~\~and the studies that have looked at an aggressive, thorough
assessment process rather than a more selective process. Have picked up
a few more cancers, but the additional cost in terms of anxiety,
additional investigations, et cetera, and no demonstrable improvement in
outcome has meant that the guidelines have not recommended routine
\~\~screening \~\~cancer screening ~~rather than so~~ the recommended
approaches are much more selective sex specific screening.

\~\~Um, \~\~it's a PSA breast assessments, that sort of thing, rather
than a, \~\~you know, \~\~CT, every bit of them, \~\~you know, \~\~all
the time. \~\~So \~\~

\*\*aminder-2021-4-18\_\_17-8-43:\*\* ~~What~~ What is the algorithm for
investigation?

**manj_gohel - denoise:** ~~so~~ it's a really good question because
most vascular surgeons don't have a clue about \~\~sort of
\~\~algorithms because they're all done by a nice ~~strong boast~~ nurse
led thrombosis clinic in our $$00:37:00$$ hospitals. \~\~And \~\~again,
~~it's,~~ I think it's important that we understand how these algorithms
work. So the most important components.

Is the first component of the algorithm, which is an assessment of the
pre-test probability of DVT. So anyone who comes with a DVT, you can go
through a validated\~\~ , um, \~\~tool. And the most common is the
Wells, ~~a~~ probability school, which would all have heard of series of
questions and give you an indication as to whether a DVT is likely or
unlikely.

If a DVT is likely, then the algorithm is to do a scan, very
straightforward. If a DVT is unlikely, then the algorithm is to do a D
dimer. Because if that is negative, DVT is excluded 30 to go anywhere
near a scan, no confusion. \~\~Um, \~\~and so there is, and again, the
guidelines are very clear on the assessment process, but a lot of this
won't reach our radars as vascular specialists at all until the DVT has
been diagnosed.

So we don't appreciate the importance of the $$00:38:00$$ early stages.
\~\~Um, \~\~So again, have a quick plug for the guidelines. Again,
there's a very nice algorithm, beautiful colors. I definitely recommend
having a look.

**andrew_nickinson-denoise:** so the exact choice and duration of
anticoagulation in the management of a DVT is probably beyond the scope
of this podcast, but on the whole are DOACs preferred over vitamin K
antagonists, such as warfarin and why.

**manj_gohel - denoise:** ~~Um, so~~ in a word, yes. \~\~Um, so lots and
\~\~lots and lots of studies funded by big companies that make DOACs
have been done and they've all shown fairly consistent things. ~~So~~
they've shown that the DOACs are as effective as the vitamin K
antagonists\~\~ , um,\~\~ at preventing DVT. So preventing recurrent
DVT. So they're as effective in terms of anticoagulation.

They have almost always a significantly lower. Bleeding risk, but
they've got this enormous added convenience of not needing regular blood
tests, et cetera, not having this dietary\~\~ , um, \~\~effect that the
vitamin K antagonists can have and, \~\~you know, \~\~the $$00:39:00$$
erratic control, et cetera. \~\~So, \~\~so the general direction of
travel is inexorably towards more and more use of dialects.

~~Um, so~~ a couple of other areas where darks are really Shaun. ~~So~~
the tendency is to recommend longer courses of anticoagulation and often
indefinite anticoagulation. a number of studies, both rivaroxaban and
apixaban have looked at the effect of a lower dose of Dohuk in these
patients. So if you need to extend anticoagulation, can you use a lower
dose, a prophylactic dose, so 10 milligrams of rivaroxaban or two and a
half BD of a pixel.

And. The results have been \~\~really, \~\~really impressive because the
prevention of recurrent VTE is very good to the same as the therapeutic
dose, but the bleeding risk is much lower. So you've got this additional
benefit of being able to give an Eva load those with even lower bleeding
risk. \~\~Um, \~\~and the additional, \~\~the sort of the, \~\~the real
icing on the cake for the deluxe has been a few recent studies that have
been looking at cancer patients.

~~Um, so~~ traditionally cancer patients where, ~~you know,~~
$$00:40:00$$ low-molecular weight heparin only, not for DOACs. \~\~Um,
~~there's not enough evidence~~ , but,\~\~ but the hopper size study and
the Caravaggio study more recently have both looked at the docks or ban.
And I think apixaban in the context of cancer and have shown that
actually they're very effective.

\~\~So, you know, ~~almost all of the. Areas~~ , um,\~\~ DOACs are
demonstrating their superiority. \~\~Um, um, ~~the one very notable
exception is antiphospholipid syndrome, particularly triple positive
antiphospholipid syndrome. This is a pretty nasty acquired
thrombophilia~~ , um,\~\~ which is\~\~ , um, \~\~where warfarin is still
the gold standard.

\~\~So, \~\~but pretty much everything else is done.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* patients with a proximal DVT. So a
DVT in the eyes of your femoral or the femoral popliteal segment. Is
there a role for elastic compression in the acute phase?

**manj_gohel - denoise:** \~\~So, um, \~\~ traditionally people have
been a bit nervous about putting compression on patients with acute DVT,
\~\~you know, sort of \~\~ concerns about causing propagation and
causing PEs and all this sort of stuff. \~\~Um, so, um, ~~again, a very
important study was the ideal DVT study~~ , um, ~~run by a series of
Dutch colleagues~~ , um,\~\~ and a number of other additional
$$00:41:00$$ studies more recently that have built on the original idea
of DBT study.

And \~\~that the, \~\~the short answer to your question is that early
compression is \~\~really, \~\~really, really important. It's a really
positive thing to do within 24 hours and it's proper compression and
it's not just the Ted stocking and see what happens. It's 30 to 40
millimeters of mercury. So that in practice is a class two stocking with
a bandage on top.

\~\~Um, \~\~and the benefits are reduces the early pain and swelling of
the DVT, but also interestingly, It reduces the risk of post-thrombotic
syndrome. \~\~So, \~\~so again, let me say that again. So if you put
compression on early, it reduces the risk of them developing
post-thrombotic syndrome. So a lot of focus has been on clearing the
vein and early thrombus removal and thrombolysis and thrombectomy and
all this sort of aggressive stuff.

But just by doing the compression, we can have at least part of the same
effect and we've just not been doing it. \~\~And, \~\~and, \~\~you know,
\~\~you guys know in the hospitals, \~\~there's, you know, very,
\~\~very rarely do these patients get proper compression. \~\~Um, \~\~so
again, there's a $$00:42:00$$ big section in the ESPs guidelines about
the role of compression and our group with them as to when to use it.

How long do you use it for? \~\~Um, \~\~and what we want to see now is
the DVT pathways around the country, around the world, updated and
amended with this latest guidance.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* one of the concerning
complications of a DBT, particularly a proximal DVT is post-thrombotic
syndrome. Can you recap the symptoms of PTs and how it's diagnosed?

**manj_gohel - denoise:** yes, of course. \~\~So, um, it's, \~\~it's a
fairly amorphous entity PTs. ~~It's a , um,~~ it's a series of\~\~ ,
um,\~\~ Patient symptoms and clinical signs that develop after deep vein
thrombosis. \~\~Um, \~\~that's deliberately very vague because the
condition is so variable. \~\~Um, \~\~and in terms of diagnosing PTs,
\~\~I mean ~~the official diagnostic tool is~~ , um,\~\~ a score of five
or more on the scale, but to is another one of these\~\~ , um,\~\~ tools
that have been developed for\~\~ , um, \~\~measuring both making a
diagnosis, but also assessing progression of PTs.

\~\~Um, ~~but in terms of sort of centers, people get swelling,
heaviness pain, there's~~ $$00:43:00$$ a very unique symptom, which has
been this good occasion , um,\~\~ which is almost pathic and monic of
post-thrombotic syndrome will venous outflow obstruction. And it's
\~\~this, ~~this is pain~~ , uh,\~\~ which has a bursting tenths quality
in the calf on exertion.

Which does settle on stopping, but it takes a lot longer than ideal
publication. So sometimes people will take half an hour to get better.
The link has to be elevated. So that's been as qualification and that's
often the most disabling symptom. \~\~Uh, \~\~but of course, people can
develop the same sort of clinical complications than you can with any
venous disease.

\~\~Um, uh, \~\~skin changes, hyper Dematic sclerosis, venous leg
ulcers, et cetera. \~\~So, \~\~so \~\~that's, \~\~that's PTs and it's
\~\~up to \~\~up to 50%, probably closer to 25% of proximal DVT.

**andrew_nickinson-denoise:** ~~um, before we move on to talking about
post-thrombotic syndrome,~~ a quick question about\~\~ , uh,\~\~ IVC
filters as vascular surgeons, we sometimes get asked about the
appropriate limits of inserting an IVC filter. When would you consider
one and how long can one stay in situ for.

**manj_gohel - denoise:** \~\~Um, \~\~so short answers virtually never,
and as soon as possible. \~\~Um, so, \~\~but \~\~let's, ~~let's expand
on that a~~ $$00:44:00$$ little bit. So the history of IVC filters is a
painful story , um,\~\~ particularly in the U S super aggressive use of
IVC filters. \~\~Um, \~\~very few of them retrieve lots of IVC,
occlusions, major lawsuits against big companies.

\~\~So, you know, \~\~very sorry story. \~\~Um, \~\~and that's led to a
worldwide. Reluctance to use IVC filter. So probably in some cases we
should be using them. We haven't been using them, but the traditional
~~sort of~~ indications and reasons for using IVC filters included weird
and wonderful things like floating thrombus and \~\~you know, \~\~other
factors.

\~\~Um, \~\~the reality is the only real indication that we could come
up with was when there's a proximal DVT, and there's a clear
contra-indication to anticoagulation. So if there's no anticoagulation,
then the risk of propagation of P is reasonably high. So a temporary IVC
filter in that case, there's a strong case for if a patient is
anticoagulated.

\~\~Very, \~\~very rarely can the case be made for an IVC filter. Very
rarely. And $$00:45:00$$ I don't want to go into nuanced details. \~\~I
mean, \~\~there's a, there a weird and wonderful is where somebody
already had a PE there's right. Heart strain. There may be some
anatomical features that you're worried about there. Their anticoagulant
control is borderline, \~\~you know, there might be, \~\~there might be
specific cases, but this is really very rare.

Most people don't until quite late. You do not need an IVC filter.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* so clot burden reduction
techniques are a hot topic at the moment. Before we talk about endo
Venus techniques, is there a real full surgical Venus thrombectomy? And
when would you consider this?

**manj_gohel - denoise:** ~~Yeah. So, so~~ open thrombectomy is part of
the spectrum of early thrombus removal techniques. It used to be very
popular, a very satisfying technique. I think I've done it three times.
They've all been for the same sort of indication, which is flag Amaziah
severe limb threatening\~\~ , um,\~\~ post DVT change. And in a patient
where they couldn't tolerate anticoagulation and therefore weren't
candidates for thrombolysis.

So you're in a patient where the leg is $$00:46:00$$ threatened. You
can't anticoagulate them, you can't thrombolize them. And then what do
you do well in that case? \~\~Well, ~~then potentially thrombectomy may
have a role~~ , um, \~\~as a sort of last ditch approach. But in that
sort of, if that's not the case, then almost always a catheter based
approach is less invasive ~~it's.~~

\~\~Um, \~\~it's more acceptable. \~\~Um, ~~also it's people who've got
more training. I~~ I mean, \~\~open thrombectomy is it would be very
interesting \~\~for, \~\~for trainees to read some of the descriptions
of open thrombectomy. \~\~I mean, it's a, ~~it's a very satisfying
technique, but it's quite involved. It involves~~ , uh,\~\~ finding and
exposing the femoral Refunder and superficial femoral veins.

It's, \~\~you know, ~~prying tight compression around the lower leg to
milk the clots out~~ , um, \~\~from this deletes approximately. So the
original descriptions are really interesting. \~\~Um, \~\~but really
very rarely would we need to do that.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* so you've mentioned catheter
directed techniques for clot burden reduction. There's been a lot of\~\~
, uh,\~\~ trials recently, which have challenged our thinking on the
appropriateness of these techniques, such as the attract and the coven
trial. What's your take on the current evidence?

**manj_gohel - denoise:** \~\~Um, \~\~ controversial. ~~Um, so, so~~ the
fundamental issue here $$00:47:00$$ is that the trials that have been
done almost certainly would not have included a large number of people
who would benefit from interventions in the opinion of the
investigators. So if somebody has got severe DVT, it is unlikely,
particularly in the U S where the attract trial was done, but these
people would have been randomized into the trial.

So the immediate criticism of the trials is that this is not reflective
of the population. Know, you've excluded the people that benefit. So
it's an underestimate of the benefit of the technique. \~\~Um, ~~but it
really that the trial results themselves~~ , um, \~\~there is a modest
benefits. \~\~Um, \~\~so in the Kavanaugh trial, ~~the quality of life ,
um, and the PTs rate that was actually~~ the PTs rate was reduced.

\~\~Um, \~\~the quality of life was less impressive, but the PTs rate
was reduced moderately. And in the attract trial, when they subgroup
analyzed the only femoral DBT group, then there was \~\~a, \~\~a
reduction in the number of people who develop moderate and severe PTs.
\~\~Um, \~\~so I think the numbers are something along the lines of
you'd have to treat 10 people with thrombus removal to $$00:48:00$$
prevent one person developing moderate to severe PTs.

So then the discussion is\~\~ , well, \~\~are those numbers needed to
treat appropriate for intervention? \~\~Um, ~~Particularly when you then
start to consider the additional need for stenting surveillance, et
cetera. So I think the jury is very much out~~ , um,\~\~ and \~\~you've
got it's, ~~it's turning into a~~ , uh,\~\~ a Brexit or a Donald Trump
like discussion.

You've got, \~\~you know, \~\~really stark, strong, firmly held
unshiftable views on both sides of the argument. \~\~Uh, \~\~and what we
need is a bit of nuance. What we need \~\~is, \~\~is everyone accepts
that some people benefit let's all work together, try and work out,
which people benefit that's work on case selection. ~~Um,~~

**andrew_nickinson-denoise:** So we'll put you on the spot then. \~\~Um,
\~\~when \~\~would you offer, \~\~would you offer thrombolysis which
patients would you offer it in and which circumstances would you also
stent?

**manj_gohel - denoise:** so ~~we,~~ we have them thrombolysis \~\~um,
\~\~we've got a pretty big deeply in this practice. \~\~Um, ~~but.
Pretty reluctant use of thrombolize is~~ is everybody gets if somebody
is being considered for trombone. Well, \~\~ first of all, there's no
role for thrombolysis in anything other than only a femoral segment. So
if it's inferring when or DVT, but it's approximately even for the
$$00:49:00$$ legacy severely symptomatic, but studies have showed that
actually you cause harm by attempting early thrombus removal is that's
the first important point.

Even if they have got severe symptoms, there's always a role for
conservative management, compression elevation. And a lot of these
people have a dramatic improvement in their symptoms. \~\~Um, \~\~if
they don't and there's an honest discussion ~~then potentially,~~ and
the bleeding risk is low\~\~ , um,\~\~ then potentially there is a role,
but when there's a treatment with a borderline benefit or the benefit is
unclear, then I think what we've gotta do pick low risk patients.

So low bleeding risk, we've got to choose teams and techniques with the
highest risk of technical success. And we've got to pick people where we
think the benefit is greatest. I, those that have the highest risk of
PTs, so \~\~that \~\~those are \~\~sort of \~\~questions. ~~I think~~
you've got to ask yourself is living with slow.

Have they got a high risk of PTSD, but didn't do anything. And can I do
the technique with a high level of technical success? If they answer
those questions are appropriate, then that's the time to proceed whether
or not you $$00:50:00$$ stent is \~\~very, \~\~very difficult. ~~Um, so
we,~~ we had a case not so long ago where we had a very nice result from
early thrombus removal.

We stented, and the patients from Bose again early and subsequently was
identified to have triple positive antiphospholipid syndrome. And
obviously there wasn't the opportunity in the time to make that
diagnosis prior to the decisions around the thrombus removal. So you end
up stung and now this patient has a stent can be very difficult to open
up again.

\~\~Um, \~\~so \~\~the, \~\~the advocates and the aggressive centers
would say, you can't leave a. \~\~Uh, ~~significant stenosis after
thrombus removal, otherwise away from Bose. Whereas others will say~~ ,
well,\~\~ hang on. If we go back to the early studies, like Kevin's
\~\~very, \~\~very few. If any people actually had stents, but actually
their results were still reasonable.

\~\~So, you know, ~~it's difficult. I think once you get on the roller
coaster of thrombus removal, it's very difficult not to then proceed
also to stenting. If you see a significant lesion, for example, at the
mater and appoint~~ , um,\~\~ final comments I make is that the use of
recanalization and stenting for chronic PTs is a very effective
$$00:51:00$$ technique.

And so another approach, if you're not sure is to manage them
conservatively, but always have that up your sleeve\~\~ , um,\~\~ that
if they get significant PTs at six months, no earlier then we could
potentially consider recapitalizing and stenting at that point.

**andrew_nickinson-denoise:** ~~and then does he think we should just go
back quickly? We jumped question 21. Um, just to talk. Yeah. Do you want
to, do you want to just ask that one? I think it'll be quite nice
introduction to that animal section.~~

\*\*aminder-2021-4-18\_\_17-8-43:\*\* ~~I'll just skip to asking about
PTs. Maybe that might be a better thing to do, do you think?~~

**andrew_nickinson-denoise:** ~~Uh, can I get, I I mean, we can edit it
around. Call me so.~~

\*\*aminder-2021-4-18\_\_17-8-43:\*\* \~\~Yeah, of course. Um, so w \~\~

**andrew_nickinson-denoise:** \~\~Well, we'll skip back a part, sort of
go back to where we were. Um, we were talking about the license. So, um,
\~\~following from the lysis, what duration of anticoagulation is
required?

**manj_gohel - denoise:** ~~So, so~~ the whole point of anticoagulation
after DVT is to reduce the risk of propagation and pulmonary embolus,
firstly, but also then to reduce the risk of recurrent VTE. So those are
the two main names of anticoagulating people. \~\~Um, \~\~and the aims
don't really change if you thrombolyzed or if you put a stent in
~~now.~~

~~So it was~~ some people used to say, Oh, I put a stent in we've
treated the Maita. No, that was the main cause of DVT. So we can stop
the anticoagulation \~\~that \~\~that's not the case. So it shouldn't
change it \~\~shouldn't \~\~certainly shouldn't be any shorter if you've
thrombolize and put a stent in. Now, whether it should be longer because
you put a stent in that's debatable.

Some $$00:52:00$$ people have very aggressive anticoagulation protocols
after stenting, but that's to do with the stent rather than the DVT.
\~\~Um, \~\~so I'm not sure if that sounds a new question, but I think
remember the aims, which are to reduce the risk of recurrent DVT and PE.
And to stop propagation of the current event.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* ~~so~~ some patients may present
with very profound, lower limb swelling. Pain and cyanosis with a threat
to viability of the limb. Can you explain for us what flag Misa is and
an approach to treatment?

**manj_gohel - denoise:** ~~So, um, so like maize, you,~~ there's two
sorts of like Macy that are\~\~ , uh,\~\~ described. \~\~Um, \~\~and to
be honest, ~~I think,~~ I don't think anybody has a\~\~ , uh,\~\~ a
detailed and robust understanding of what these actually mean. \~\~So
\~\~, but maybe say Alberto lens. So Alba is \~\~the, \~\~the white leg.
Karelia is the severe. Form a flag measure.

\~\~mean, \~\~theoretically, it's got a limb loss rate of 30 or 40%
severe limb threat compartment, syndrome, skin, blistering, swelling, et
cetera. \~\~Um, \~\~the reality is that \~\~it's, \~\~it's often
overdiagnosed, so you'll see a lot of people saying I did being
assembled licensed $$00:53:00$$ for flatmates you, and it's just a big
swollen in Gorge leg.

The reason it happens is almost certainly a profound obstruction of
venous outflow. So the venous blood in the leg cannot escape. You get
\~\~this, ~~this cycle of worsening pressure~~ , uh,\~\~ leaking ~~of ,
uh,~~ of fluid from the Capella is increasing pressure, increased
specialist, soft tissues. And then that starts to threaten tissue
perfusion and potentially if it's bad enough that cappelary even the
arterial pressure will, the competitor is threatened the actual arterial
profusion of the leg as well.

So that's the sort of most severe and extreme form. \~\~Um, \~\~I don't
think anybody has confidently linked. The anatomical findings and
features of a DVT to what the leg looks like. \~\~Um, ~~I've never been
never ceased to amaze me. There was a patient I saw who literally had~~
, um,\~\~ a thrombose \~\~um, \~\~every deep vein thrombosis from the
IVC down to both lower legs and was almost asymptomatic or Q3 was almost
asymptomatic.

\~\~So, \~\~so we've got this very uncomfortable lack of understanding
between the $$00:54:00$$ symptoms and the clinical and anatomical
pattern of DDT.

**andrew_nickinson-denoise:** ~~right. So shall we move on? We've got a
few more questions to talk about. Um, uh, approximate, deep venous
insufficiency. Um, what have we got here? Sort of five or six questions,
and then we can probably wrap things up to a close then identify what
your feeling is if you have time.~~

**manj_gohel - denoise:** ~~Carry on, carry on guys.~~

**andrew_nickinson-denoise:** ~~Um, brilliant.~~ So finally, let's move
on to talk about the treatment of proximal deep venous insufficiency.

\~\~Um, \~\~and when we talk about that, we're talking about obstruction
\~\~and, \~\~and competence. What are the common causes for deep venous
obstruction? Thinking about \~\~sort of \~\~post-thrombotic and
non-thrombotic obstructions.

**manj_gohel - denoise:** \~\~ \~\~ so again, the terminology is
important. So it's venous outflow obstruction. \~\~Um, ~~obstruction
implies that there's a physiological barrier causing the consequences as
opposed to occlusion, which is an anatomical term. So term is Venus
outflow obstruction, and essentially anything that reduces the ability
of~~ , um,\~\~ venous blood to escape the leg via deep venous channels
will cause an obstruction.

And again, going back to a bit of physiology. So I always forget, I
think it's Percy's law that talks about the flow rates being the fourth
power of the radius. \~\~Um, \~\~so it's really interesting. Yeah, a
question to ask is if you've got a two centimeter vein, $$00:55:00$$ how
many, one centimeter veins would it take to carry the same potential
flow as a one, two centimeter beam?

And the long story short is that it takes 16 one centimeter veins to
carry the same amounts of potential flow as one, two centimeter vein. So
it doesn't take much of a narrowing to have a great potential impact on
flow. And of course, most of the time you don't need that flow
potential. \~\~You know, \~\~it's only an absolute extremes \~\~of,
\~\~of circulatory stress that you'll need that sort of potential, but
\~\~it, it, \~\~it is interesting.

And again, it also challenges when people say, Oh, there's great
collaterals. \~\~That \~\~that'll be enough. \~\~Well \~\~we'll know,
unless they're enormous, \~\~you know, \~\~you need 16 of them \~\~to,
\~\~to have the same potential. \~\~Uh, \~\~blood carrying capacity.
\~\~Um, \~\~so in terms of the causes, \~\~I mean, \~\~lots and lots of
goals, the most common by far is post-thrombotic disease.

So when you've had a DVT, one of three things happens. If you're lucky,
the vein will recanalize completely, if you're unlucky, it will obstruct
completely. And if you're somewhere in between, you'll end up
$$00:56:00$$ with partial stenosis and obstruction. \~\~And, \~\~and
what's important is even if the vein is open, what you almost always
lose in the post-thrombotic vein is a lack of compliance.

Isn't, \~\~you know, \~\~it's not the same compliant vein that can
respond to demands and physiological need that you have, which \~\~in a,
~~a, in a primary non~~ , uh,\~\~ scarred vein\~\~ , um,\~\~ other
potential causes are. So this idea of a non-thrombotic early at vein
lesion, or may turn a lesion. So may turn again, the original paper,
1953 is very interesting reading.

\~\~Um, ~~there were a couple of Austrian~~ , um, ~~pathologists who
were looking at kind of various specimens and they identified that a
very high proportion of people, particularly those had left-sided DVT
hard, not only the~~ , uh,\~\~ overriding iliac artery causing
compression, but they had a secondary fibrosis tight fibrosis in the
iliac vein.

So it's not just the compression. It's not just the fact that it's
squashed because any one of us in a certain position we'll have a
squashed vein. It's the fact that there's a $$00:57:00$$ secondary
inflammatory fibrotic change, which is what's causing the obstruction.
So that's a true may turn or non from what's it lesion.

\~\~Um, ~~and the other big group of patients of course, is malignant~~
, um, \~\~lymph node or retroperitoneal fibrosis related venous outflow
obstruction, but post-thrombotic by far was the most communist diagnosis
mythology.

**andrew_nickinson-denoise:** \~\~I thought you got to put me on the
spot though and asked me a very difficult maths question. So I'm
slightly relieved about that. Um, and, ~~and outpatient clinic~~ ,
we,\~\~ we may see patients who come in with\~\~ , um,\~\~ severe venous
disease. \~\~So, you know, \~\~coming in with finished skin changes, for
example, when would you consider actually imaging the ~~deep , um,~~
approximately deep veins in addition to superficial and deep veins in
the leg and what are the best modalities to do this?

**manj_gohel - denoise:** \~\~um, \~\~so it really getting down \~\~to
the, \~\~to the sort of crutch of \~\~the, \~\~the importance of a
detailed assessment of the entire supervision deep system. \~\~So, so
\~\~every patient with venous disease should have a whole leg inferring
when or duplex to start with. So that's deep and superficial veins. So
there's no real role for just looking at superficial veins.

So you $$00:58:00$$ need to understand the context in terms of their
structure they're and if they're refluxing to understand the context\~\~
, um,\~\~ and again, remember that. Reflux on a duplex. Yes. All we see
is arrows going in certain directions, but all reflux means is that
after a car fork, mentation maneuver, there is some retrograde flow in a
superficial vein, more than half a second in a deep vein, more than one
second.

That's all it means. So for example, you can have retrograde flow for
0.6 seconds in a saphenous vein, and that will be labeled, defined as
reflux for all the rest of the time that superficial vein is doing the
right job, it's returning the blood to the heart. So just \~\~be, \~\~be
wary of interpreting what these arrows mean.

\~\~Um, \~\~and in terms of how that affects your decision-making. First
of all, one approach is to consider the overall burden of venous
disease. And these people are being as hypertension. And what I try and
do is draw a pie charts and say, you got to be this hypertension. You've
got venous disease, and here are the different causes of your venous
disease.

And $$00:59:00$$ that might include superficial reflux, deep venous
reflux, deep into the obstruction, other factors. And you \~\~sort of
\~\~try and, \~\~you know, \~\~apply \~\~some, \~\~some clinical
judgment as to what the different factors are. Now. Even if they've got
significant, deep venous reflux and superficial venous reflux, there is
still a role for treating superficial reflux.

In most of these cases, I still come across colleagues and other people
who say, look, you shouldn't treat the superficial veins if there's the
reflux. \~\~Um, \~\~but all the studies ever Escar have shown
significant benefits, even if there's equally flux. \~\~So, \~\~so
again, key message is treat the superficial reflux.

If it's there now, venous obstruction and looking for it is a different
matter. \~\~Um, ~~there are~~ , um,\~\~ again, lots of approaches or
some people are very aggressive about evaluating the iliac veins.
\~\~Um, You know, \~\~CTVs on everybody Iverson. The problem is if you
get super aggressive, then you start to over-diagnose and if you start
to over-diagnose, you start to over treat and this all gets very messy.

\~\~Um, um, ~~I think the sort of people~~ $$01:00:00$$ that have got
clear signs and symptoms of major venous outflow obstruction,
particularly things like being a school education history of previous
DVT, really disproportionate Venus changes to the superficial and the
inferring mineral imaging. Those are the people that image , um,\~\~ and
~~on the soup~~ on the duplex imaging of the leg, if there are changes
in the common femoral vein that make you think there's a proximal
problem, particularly a loss of faces, city of flow\~\~ , um,\~\~ then
that's pretty\~\~ , uh,\~\~ concerning for a significant venous outflow
problem.

\~\~Um, \~\~so again, the face the city, \~\~I mean, \~\~there should be
in an unobstructed venous system. The common femoral vein should really
reflect the right hearts. Which has some faces city. So there should be
\~\~some, \~\~some transmission of that basis, city and respiratory
phases, city. \~\~Um, \~\~so if that isn't there, then you're thinking,
hang on.

There's something interrupting that transmission, which is almost always
an obstruction somewhere. So those are the people \~\~I'd \~\~I'd image,
but I wouldn't over image. \~\~Um, \~\~because then you end up with a
headache and a problem. Should I treat you to not treat?

**andrew_nickinson-denoise:** ~~Go down the rabbit hole.~~

\*\*aminder-2021-4-18\_\_17-8-43:\*\* \~\~so, so you, ~~so you mentioned
IVIS~~ , uh,\~\~ what is $$01:01:00$$ intravascular ultrasound and what
are the particular benefits of using this technique over save, you know,
graphy alone.

**manj_gohel - denoise:** Diverse is a, B mode only intra venous or
intravascular\~\~ , um, ~~ultrasound modality. So it's an approximately
nine French probe that is inserted into the vein. And it gives you a
three 60 degree view in bimodal. Lisa, not color flow, just B mode. Of
the~~ , uh,\~\~ anatomical structures. \~\~Um, \~\~and \~\~what it,
\~\~what it's \~\~very, ~~very useful for is identifying venous anatomy,
confluences~~ , um,\~\~ identifying the size of veins.

So it allows you to plan sizes of stents. \~\~Um, \~\~and it really is
an important adjunct to be no gruffy in other modalities. \~\~Um, \~\~so
again, we did our first 30 or so cases of deep venous stenting without
IVUS and thought we were brilliant and IVUS was a waste of money. And
then we started using over some thought preliminary.

I can't believe we were doing this without. It's \~\~like,
\~\~$$01:02:00$$ satnav, \~\~you know, \~\~once you start using it, you
suddenly realize that there, \~\~you know, it's, \~\~it's a really
useful items. \~\~Um, ~~so in terms of when you use it~~ , very,\~\~
very rarely per diagnostic. So it's not really used for diagnostic,
although in some parts of the world it's commonly used for diagnostic
because the risk of over-diagnosis.

But \~\~very, \~\~very commonly, almost routinely for therapeutic,
particularly when we're stenting the veins to plan our landing zones.

**andrew_nickinson-denoise:** \~\~I mean, you, \~\~you talked about
over-diagnosis. Can you talk us through some of the decision-making
processes that you go through when you're assessing a patient who has a
deep venous obstruction?

**manj_gohel - denoise:** there are lots of patients that have this
anatomical change. \~\~So \~\~the number of referrals I get from people
who have done a CT and they've picked up a problem. \~\~So \~\~the most
important thing is the clinical status and the clinical picture. \~\~So
\~\~have they got symptoms go about right at the beginning of the
podcast?

Have they got symptoms? Have they got complications? And if they haven't
got significant symptoms and they haven't got significant complications
and there's not really an indication for treatments. \~\~Um, ~~so leg
swelling~~ , um,\~\~ $$01:03:00$$ was. Initially frequently pushed as a
Oh you're swelling will get better if we get rid of your obstruction.

That's only the case in probably less than 50% of cases. \~\~Um, ~~and
the reason for that is that when you, yes, the original etiology for the
swelling may well have been Venus, but you almost always get a secondary
lymphatic disfunction when you've had swelling. For whatever reason,
whether it's heart failure, whether it's Venus~~ , the, \~\~the
lymphatic system gets damaged.

And so even if you get rid of the original\~\~ , uh,\~\~ cause the
lymphatic damage persists, of course, and the swelling persists. \~\~So,
um, ~~the symptoms are very important. And~~ , uh,\~\~ in terms of
complications, \~\~I mean, you know, \~\~if somebody obviously got
intractable ulceration, et cetera, these are all important became
patients, but a bit of skin change a bit of, \~\~you know, \~\~mild
swelling, you know, careful case selection is very important for these
procedures.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* so following a deep venous
recanalization and standing, what surveillance do you offer for those
patients?

**manj_gohel - denoise:** surveillance has been evolving. \~\~Um, so
the, ~~the first~~ $$01:04:00$$ availability for , um,\~\~ CE marks DB
in the States in the UK was around 2012. \~\~Um, \~\~and ~~so~~ the
\~\~service \~\~services across the country really got started at a few
centers in 2012, 2013. \~\~Um, \~\~initially there was an early scan and
then a scan maybe at six weeks and, \~\~you know, \~\~three or six
months down the line.

I think we realized that in general, the people that developed problems,
often development very early. So we are scanning these people the day
after the intervention. Obviously there's interoperative quality control
and venograms and scanning, but the day after the intervention to ensure
that there's no early thrombus\~\~ , uh,\~\~ problems.

And then a couple of weeks to make sure that there's nothing that's
happened in the first couple of weeks, because there's an opportunity to
re intervene to, to balloon, to correct any technical issues. At that
point, after that point, it's usually six weeks, three months, six
months, and then annually thereafter.

So that's a sort of protocol that we have. \~\~Um, \~\~and in general,
what we've seen is that people that develop problems tend to develop
them relatively early. So once you get to a year, then in general, the
$$01:05:00$$ patency rates are \~\~very, \~\~very good. ~~And, and as,
as you , um, as you know them in doing our,~~ in our center, that the
chronic PTs stenting\~\~ , um, PA\~\~ primary patency rates at around
three years are over 80%, 80, 85% is what you can expect in these
patients.

Of course, there are some that have problems, but it's important to,
~~again, to~~ remember that even those that have thrombosed, they
generally go back to the level of symptoms they have prior to
intervention. That's very reassuring. The last thing you want to do is
to make people worse \~\~with a, \~\~with a novel intervention.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* And so what about your
anti-coagulation and anti-platelet regime for these patients?

**manj_gohel - denoise:** \~\~so, um, \~\~ there was a systematic review
done a few years ago where all of the published literature for deep
venous stenting was reviewed. And I think the authors identified 28
different regimens for anticoagulation of the stenting. \~\~Um, so, um,
\~\~the honest answer is nobody knows. \~\~Um, ~~our approach is to~~ ,
um,\~\~ to have low molecular weight heparin as the primary
anticoagulant for the initial two week period. And then at the two week
point, they undergo a stent. If there's no issues, they $$01:06:00$$ get
transitioned to a DELAC. In addition, the patients get six weeks of
clopidogrel as an anti-platelets. \~\~Um, ~~and again, the reason for
that is that~~ , um,\~\~ it's a foreign material into the vein. Yes. The
role of anti-platelets of renting venous thrombosis is very limited.

But there has to be some platelet related activity and platelet
activation involved there. So it \~\~sort of \~\~makes logical sense to
have some anti-platelet activity. \~\~Um, \~\~of course the downside is
that there's an increasing bleeding risk. So this is the sort of, these
are the constant tightropes that you're walking with these patients.

**andrew_nickinson-denoise:** \~\~and finding the, we \~\~we've talked
about endovascular and Venus treatments, but is there a role for open
surgery in these patients?

**manj_gohel - denoise:** \~\~Um, \~\~so in the IDX segment, very
rarely. \~\~Um, \~\~so in some patients, yes, you can do PTFE,
reconstructions and bypasses. And of course the traditional operations
of Parmadale bypass and the may who's in the type procedures. \~\~I
mean, they all, \~\~they all sounded very elegant in the books, but the
reality is a great sadness vein $$01:07:00$$ going across the lower
abdomen to the other side.

\~\~Um, ~~is not really going to sort the problem out in an enjoyable
way~~ , uh, \~\~for all sorts of obvious reasons, the size of the vein,
the pressure and all that sort of stuff. So there's really very limited
role for those sorts of procedures. Now, the one area where there may be
a role for open reconstruction is in the common femoral vein.

~~Um, so the, the consists,~~ the consistent observation is that good
inflow is absolutely imperative to get good outcomes in these patients.
And sometimes if the common femoral vein has got a lot of scarring, then
it's very difficult \~\~to, \~\~to be able to reconstruct that inflow
endovascularly. \~\~Um, ~~and so a number of authors have advocated the
use of, and the phlebectomy~~ , um,\~\~ opening up the common femoral
vein\~\~ , uh,\~\~ cutting out the scarring and the tribulations,
putting a patch on it.

Sometimes even putting an AB fistula little six millimeter graph from
the comment from an artery onto the vein to really drive the flow
through the stent. \~\~Um, \~\~it's a pretty complicated operation and
you imagine \~\~you're, \~\~you're dissecting down. There's lots of
little veins everywhere else. And lymphatics the $$01:08:00$$
complication, the wound complication rate is \~\~very, \~\~very high.

So really very limited role only. \~\~Um, \~\~the endovascular is really
the way forward for these patients ~~speaking.~~

\*\*aminder-2021-4-18\_\_17-8-43:\*\* \~\~so finally, let's talk about
pelvic confess. Sorry, start again. Okay. Um, so, um, \~\~ so finally,
let's talk about pelvic congestion syndrome. What is pelvic congestion
syndrome and how does it present?

**manj_gohel - denoise:** \~\~Um, so \~\~it often doesn't present
anywhere near a vascular surgeon. \~\~Um, ~~so there are a number of~~ ,
um,\~\~ of ladies who present with these chronic heaviness and dragging
symptoms in the lower abdomen. There may be some \~\~association with
\~\~association with men, seas there's often dyspareunia and a whole
variety of other symptoms.

There may be associated\~\~ , um,\~\~ Volvo viruses or Hosteria\~\~ ,
uh,\~\~ buttock and five-hour seas\~\~ , um,\~\~ all\~\~ , uh,\~\~ as a
result of pelvic venous incompetence. \~\~Um, \~\~but it's a complicated
field. \~\~Um, ~~there are some people that have pelvic symptoms.
There's some people that have the varicose veins or something, we'll
have a combination of the two~~ , um,\~\~ And almost always they will be
seen and initially assessed by the gynecology teams rather than coming
to the vascular surgeons.

**andrew_nickinson-denoise:** and when we do see these patients, are
there any $$01:09:00$$ treatment options available for them? And when
would you consider treating

**manj_gohel - denoise:** \~\~Uh, \~\~ in a highly selective way. ~~Um,
so the difficulty again, so~~ this is venous disease in a nutshell, the
association between anatomical changes and clinical symptoms is ropey at
best. \~\~Um, ~~in terms of post partum~~ , um,\~\~ women, an enormous
proportion of these\~\~ , uh, \~\~ladies have got venous reflux in the
pelvis. If you look hard enough.

\~\~Um, \~\~and so the problem is if you start looking for \~\~like
\~\~may Turner syndrome, if you start looking hard enough, you start
identifying these symptoms and then you lose the. The ability to really
discern who's going to benefit most. So again, I would go back to
clinical symptoms as the single most important thing.

If they've got severe clinical symptoms\~\~ , um,\~\~ measuring,
affecting their quality of life and associated significant venous
changes and those that people are trying to intervene\~\~ , um,\~\~ it's
not necessarily a benign procedure. \~\~So, um, ~~pelvic vein
embolization~~ , um,\~\~ involves implantation of\~\~ , uh,\~\~ of
coils. \~\~Um, \~\~there's concerns about non-targeted embolization
calls have ended up in lungs.$$01:10:00$$

There are a number of people with unknown\~\~ , uh,\~\~ nickel allergies
that have problems with these coils. \~\~So, \~\~so again, it's not an
area to be over aggressive. \~\~Um, \~\~and so careful case selection is
important. ~~Um, so there, there are, there are a number of , um,~~ so
again, a quick plug for the ESPs guidelines to the ~~Venus , uh,~~
chronic venous disease guidelines that are currently being rewritten,
and there'll be published towards the end of this year.

I think early next year. And there's a \~\~very, \~\~very good section
on pelvic venous disease assessment. What's very important is again, to
differentiate pelvic venous, pelvic congestion syndrome, to pelvic
origin, very costly. And one thing that is certainly being advocated as
\~\~if, if the, \~\~if the varicose veins are coming from the pelvis,
but there's no pelvic congestion syndrome, it's perfectly reasonable
just to deal with the visible varicosities from below with some foam
sclerotherapy or other treatment from below, rather than being super
aggressive embolizing from above.

\~\~Um, ~~but I think anybody who's involved in managing this really
needs to work closely with the gynecologists that are going to college,
a diagnosis that need~~ $$01:11:00$$ excluding probably before we start
to address the venous disease. And there are a number of , um,\~\~
validated questionnaires and other assessment tools that are probably
quite important.

\~\~Um, \~\~so not for the faint-hearted.

**andrew_nickinson-denoise:** ~~indeed. I mean, did you have any other
questions?~~

\*\*aminder-2021-4-18\_\_17-8-43:\*\* ~~now, Mr. Gold, is there anything
else you think we should discuss~~

\~\~or you think we've got \~\~

**manj_gohel - denoise:** ~~maybe, maybe one quick thing about training
and the future role of Venus. Um, there's been a sub-specialty in for
vascular trainees and vascular future. So that might be quite a good
middle question. So what do you think of something along those lines?
Um, I'm slightly biased and very passionate, but I think it's
important.~~

\*\*aminder-2021-4-18\_\_17-8-43:\*\* ~~Andrew, what do you think? You
want me to rephrase the question?~~

**andrew_nickinson-denoise:** ~~Yeah, I I mean, for me on the spot now ,
um,~~

\~\~what should I say , um, regards to Mr. Gold with regards to , uh,
trading, or should I , uh, don't want my patient doing things on the
spot. Um, ~~Do you think there is a role for particular subspecialty
training in venous disease~~ , um,\~\~ and particular fellowships for
trainees to take.

**manj_gohel - denoise:** I think it's a really important question,
~~Andrew. So, um, so~~ venous disease and Venus\~\~ , uh,\~\~
interventions have definitely been the Cinderella part of vascular
surgery \~\~for, \~\~for a \~\~long, \~\~long time. \~\~Um, you know,
\~\~and, \~\~you know, \~\~you could say quite rightly the focus has
been on getting technical skills in arterial disease and aneurism
surgery, et cetera, \~\~that \~\~that's all fine and important, but
there are \~\~many, many, \~\~many more patients with venous disease.

The role of vascular interventions for these patients has become clearer
than ever. \~\~Um, ~~the societal benefits, the cost benefits~~ , um,
\~\~the patient benefits are absolutely enormous. So I think it's
important that \~\~we \~\~we're almost sending the best people to be
managing these $$01:12:00$$ patients. So it's important that we grasp
the nettle and accept that.

But, \~\~you know, ~~we really need to take leadership roles in, in~~ ,
uh,\~\~ managing venous disease\~\~ , um, \~\~in terms of specific
training. \~\~Um, ~~I think it's important for people to gain as much
training during that training period as possible, but of course, augment
that with~~ , um,\~\~ with some more focus training, post CCT, if
needed.

\~\~Um, ~~I don't think everyone needs to be an expert in deep venous
stenting or complex interventions, but certainly~~ , um, ~~local
champions are needed to try and push this disease process forward and~~
, uh,\~\~ and to help this patient group\~\~ , um,\~\~ it's low hanging
fruits and \~\~it's, \~\~it's definitely something ~~we are best
managed.~~

We're best placed to manage.

**andrew_nickinson-denoise:** ~~Hmm. And I suppose a follow-up question
to that as we could talk about , um, is,~~ do you think that there is a
role for centralizing some of\~\~ , um,\~\~ more complex, deep
venous\~\~ , um, \~\~procedures? \~\~Not, \~\~not just \~\~sort of
\~\~deep venous stenting, but \~\~uh, \~\~venous thrombosis and DVT.

**manj_gohel - denoise:** \~\~Um, there's, \~\~there's always this
balance between having treatments available to as much of the population
as possible versus having that volume outcome safety association. And
the honest answer is of $$01:13:00$$ course, there's some sort of
sensible middle ground. We need more than two or three centers in the
country doing it, but we don't need every center doing it.

So I think the centers that are interested and there are plenty need to
have the local governance structures and local networks in place.
\~\~And, ~~and some sensible centralization of course is going to be~~ ,
um,\~\~ probably the way forward.

**andrew_nickinson-denoise:** Mr. Gold\~\~ , we've,\~\~ we've covered an
awful lot\~\~ , um,\~\~ in these podcasts. Thank you ever so much for
your time. \~\~Um, \~\~and equip plug, as you said, for the venous
thrombosis guidelines, which can be found on the European journal of
vascular surgery website.

\*\*aminder-2021-4-18\_\_17-8-43:\*\* It's been a real pleasure Mr.
Goldhill, having you on the podcast and we really appreciate your time.

**andrew_nickinson-denoise:** Thank you

Have a second.

**manj_gohel - denoise:** Thank you very much, guys. \~\~It's \~\~it's
been enjoyable. Thank you.

**Adam:** This episode was made in collaboration between the rouleaux
club and audible bleeding. The authors were Andrew Nickenson and a
mender Singh. The editor was Leanna and the reviewers were Adam Johnson,
initial foresight for the full outline, checkout our
[website\@audiblebleeding.com](mailto:website@audiblebleeding.com){.email}
and let us know what you think by filling out our listener survey with
the link in the show notes.

**manj_gohel - denoise:** ~~I wouldn't hang up. I wouldn't hang up.
Don't worry.~~

**andrew_nickinson-denoise:** \~\~brilliant. Well, thank you. I mean,
that's an hour, an \~\~
