---
editor_options:
  markdown:
    wrap: 72
---

# Angioaccess

**UNDER CONSTRUCTION - This Chapter is Currently in DRAFT mode**

**28 Mar 2020**: *Young Lee, MD and Matthew Smeds, MD*

```{r echo=FALSE}

library(embedr)

embed_audio("https://traffic.libsyn.com/audiblebleeding/VSITE_Revew_-_HD_Access_post_auphonic.mp3")

```

## Planning access creation

Management of Dialysis access is an important topic of discussion, not
only because it is a significant part of board examinations, but also
because healthcare costs continue to rise for ESRD patients,
particularly during the transition from CKD to ESRD. This is attributed
to use of dialysis catheters and frequent hospitalizations for
arteriovenous access failures and related procedures.

The National Kidney Foundation-Dialysis Outcomes Quality Initiative
(NKF-KDOQI) and SVS has provided guidelines in the follow
areas:[@nationalkidneyfoundation2015; @sidawy2008]

-   Timing of referral to access surgeons

-   Operative strategies to maximize placement of autogenous AV accesses

-   First choice for autogenous access

-   Choice of AV access when a patient is not a suitable candidate for a
    forearm autogenous access

-   The role of monitoring and surveillance of AV access management

-   Conversion of a prosthetic AV access to a secondary autogenous AV
    access

-   Management of nonfunctional or failed AV access

**This brings us to the question, who needs dialysis access?**

Patients should be referred to a vascular surgeon for access when their
creatinine clearance is \<25mL/min which is CKD stage 4. You want to
provide adequate time for your autogenous access to mature, so the ideal
time for access creation would be \> 6 months for anticipated need of
dialysis. This allows for time for any subsequent interventions if your
access is not maturing.

**Should prosthetic access also be placed several months before
anticipated dialysis?**

Prosthetic access patency is limited by duration of access placement,
thus, if a patient requires prosthetic access, placement should be
delayed until about 3-6 weeks before initiation of
dialysis.[@nationalkidneyfoundation2015]

**For dialysis access creation, which site should be considered and used
first?**

Due to the easier accessibility and lower infection rates, upper
extremity access sites are used first. Furthermore, you want to place
your access as far distally in the extremity as possible to preserve the
proximal arm for future accesses.

**What are some important considerations in a patient's history when
planning a dialysis access?**

It is important to find out recent history of:

-   Previous access procedures

-   Peripheral IV lines

-   Sites of any existing or previous indwelling catheters including
    pacemakers and defibrillators

-   Trauma or surgery to the upper extremities

Moreover, you also want to consider the patient's quality of life, thus,
noting which extremity is dominant is important. If possible, you want
to create your dialysis access in the nondominant arm so that when the
patient is receiving dialysis multiple times a week, they are able to
use their dominant arm during their dialysis sessions.

However, placing a fistula with lowest rate of failure is preferred to
using non-dominant hand. Therefore, placement of access on the patients
dominant side would be preferred over placement of access with high risk
of failure (i.e. on the side of an implantable cardiac
device).[@sgroi2019]

**As with any preoperative planning, physical examination is extremely
important. Central venous stenosis can cause problems such as prolonged
bleeding after dialysis sessions at the puncture site. What are some
signs of central venous stenosis?**

Unilateral arm swelling or edema and prominent venous collaterals are
signs of central venous stenosis. Central venous stenosis can lead to
venous hypertension which affects access patency and function, and also
causes disabling edema.

Beyond signs of central venous stenosis, when examining a patient, an
Allen's test should always be performed to evaluate palmer arch patency.

**Preoperative planning should also include arterial and venous
assessments. What are your size requirements for the artery and the vein
to be used in your dialysis access creation?**

First, you want equal pressure gradients in bilateral upper extremities.
If there is a pressure differential \>20mmHg or pulses are non-palpable
then patients should undergo a duplex ultrasound to evaluate for
arterial insufficiency and and the artery should be greater than or
equal to 2mm. Segmental pressures have limited applicability. Patients
with correctable lesions on duplex may consider undergoing angiography
and intervention to optimize inflow.[@sidawy2008]

A venous duplex should also be done to evaluate for diameter,
distensibility and continuity. A vein mapping is useful to determine the
size of the patient's superficial veins at various points in the forearm
and upper arm. The vein should ideally be at least 3mm, but 2.5mm will
likely dilate after regional anesthesia and be sufficient for
access.[@huber2002; @smith2012]

**Autogenous access should always be considered first due to higher
patency rates, lower infection rates, and longer duration of access
survival. What are the different configurations of autogenous
accesses?**

The first and best option would be direct arteriovenous anastomosis.
However, if that is not possible, then venous transposition should be
considered next follow by venous translocation.

Venous transposition is for deeper veins such as the basilic vein, which
is transposed so the vein lies just below the skin for easier access for
puncture during dialysis sessions. Transpositions are generally a
2-stage procedure in which the direct arteriovenous anastomosis is
created during the first stage and once the vein has arterialized 4-6
weeks later, the second stage of transposition is done when the vein is
easier to mobilize. Translocation procedures include harvesting the
femoral or saphenous vein and using it as a conduit for AV access
creation in the upper extremity.

**When can a venous transposition be done in a one stage procedure?**

When the vein is \>4mm. When a patient has not been initiated on
dialysis and there is marginal vein that would require transposition,
but carry a significant risk of graft failure then a first-stage BB
fistula may be appropriate.

When comparing single- to two-stage brachiobasilic fistula, two-stage
creation had high rates of primary patency at 2-years. However, there
was no difference in infection rate, steal syndrome, hematoma,
pseudoaneurysm, stenosis, failure rate, primary or secondary patency at
1-year or secondary patency at 2-years.[@junyanwee2018]

**It was mentioned earlier that the dialysis access should be created as
distally as possible on the extremity. What are some of the most distal
locations?**

The snuffbox fistula, which is the posterior radial branch to cephalic
direct access and Brescia-Cimino-Appel (often shortened to just Cimino)
fistula which is the radial-cephalic wrist direct access are two of the
most distal fistulas that can be created. Overall, these have comparable
patency and ischemia risk. While snuff box fistulas carry a 10% failure
rate at 1mo, the majority are able to be converted to RC
fistulas.[@siracuse2019]

**What are your arterial and venous options in the upper extremity?**

In the forearm, you have your radial, ulnar, and brachial arteries and
cephalic and basilic veins. In the upper arm, you have your brachial or
proximal radial arteries and cephalic, basilic, brachial and axillary
veins.

If adequate vein is available, most common access sites distal to
proximal include:

1.  Snuff box

2.  Radiocephalic

3.  Basilic transposition in forearm

4.  Brachiocephalic fistula - these have a few advantages over more
    distal fistulas, including higher maturation rates, decreased time
    to maturity, higher patency and functional primary
    patency.[@nguyen2007]

5.  Brachiobasilic fistula[@gilmore2006]

6.  Vein transposition from a remote site - Femoral vein transposition
    can be used for upper extremity dialysis access in patients with
    previous upper extremity access complicated by infection, thus not a
    candidate for prosthetic, but no central stenosis. There is a high
    rate of hand ischemia due to larger conduit (up to 43%).[@huber2004]

**If you need to use a prosthetic graft, what would you use?**

PTFE is the most common, they make tapered 4-7mm grafts to ensure the
size of your arterial anastomosis isn't too large to minimize chances of
steal. However, recent publications found that there is no difference
between tapered and non-tapered grafts in terms of primary patency,
steal syndrome, complication rates or need for
reintervention.[@roberts2019; @han2017]

Overall AVG have benefit of earlier cannulation, discussed later,
however they have lower patency rates and higher infection rates. There
is no difference between grafts and fistulas for perioperative morbidity
and mortality.[@macsata2019]

**For patients with central venous stenosis or occlusion, what is
another alternative upper extremity access creation?**

Two overall strategies for managing patients with severe central venous
stenosis or occlusion are lower extremity AV access of hybrid
catheter/grafts. Patency of femoral vein transposition is better than
hybrid catheter/graft placement.[@brownie2016; @glickman2011] We will
cover specifics of these techniques later.

For lower extremity AV access, femoral vein transposition has been shown
to have the best outcomes, followed by saphenous vein transposition and
graft placement. Lower extremity access should be avoided in patients
with peripheral vascular disease or lower extremity ischemic
symptoms--when in doubt perform duplex and segmental pressures to fully
evaluate. Veins should also be evaluated to ensure patency more
proximally.[@parekh2016]

For patients where lower extremity access may not be appropriate, the
hemodialysis reliable outflow (HeRO) device can come to the rescue.
These devices may not have been encountered in your training, so we will
go into detail here. This device is composed of 2 components: a graft
which is made of 6mm PTFE with a titanium coupler at one end, and a
venous outflow component of a 19 Fr silicone catheter reinforced with a
nitinol braid to prevent kinking. The graft portion is anastomosed to an
artery, usually brachial, and is tunneled subcutaneously and the venous
component is percutaneously placed into the right atrium via the IJ or
subclavian vein. The two components are connected with a titanium
coupler at the deltopectoral groove. If you need more immediate
dialysis, the super HeRO comes to the rescue in which the graft portion
is the early cannulation graft.

Hybrid catheter/grafts are good alternatives in patients with previous
line infections, central stenosis, peripheral vascular disease and no
suitable vein in the upper extremities. They have shown fewer bacteremia
episodes than catheter, low primary patency rate and acceptable
secondary patency rates.[@alshakarchi2015] Absolute contraindications
include donor artery \<3mm, inability to dilate outflow vein to 19f,
allergy to device materials (ePTFE, silicone, titanium, nitinol), and
current active infection.[@meritmedical]

## Techniques for access creation

**The techniques of arteriovenous fistula creation are common across
access sites. Can you go through the techniques?**

First the vein is identified and the distal end is transected and
flushed with heparin. By flushing with the heparin, you are able to
access the caliber and extent of the vein as well as identify any side
branches

Then after distal and proximal control of your artery, a 4-6mm
arteriotomy is made. The length is limited to decrease incidence of
arterial steal. The artery is then flushed with heparin to avoid
thrombosis during the anastomosis and an anastomosis is created between
the side of the artery and the end of the vein. A 6-0 or 7-0
nonabsorbable continuous suture should be used to create the anastomosis
to avoid future dilation of the anastomosis.

**What are some other options if an access is not able to be created in
the upper extremity?**

Autogenous accesses can also be created in the lower extremity. Femoral
artery to femoral vein or saphenous vein anastomosis can be created.
Both veins have to be transposed. Synthetic grafts have high infection
rates (as high as 22% in some series) and only a 50% patency at 6
months.[@antoniou2009; @lazarides2018; @pike2019] Risk of lower
extremity ischemia increased with burden of PVD, AV fistula vs graft,
distal arterial inflow, and large femoral vein mismatch, but can be
tempered by banding/narrowing of femoral vein at the time of
surgery.[@antoniou2009; @bourquelot2012; @gradman2005]

Access creation in the chest wall or cervical region is also possible
with axillary artery to ipsilateral axillary vein loop access, axillary
artery to contralateral axillary or jugular vein straight access (ie
necklace access) and brachial artery to jugular vein straight access.
Keep in mind that for these fistulas, the central veins must be patent.

**Are there benefits to different anesthetic techniques used during
access placement, such as regional anesthesia?**

Regional anesthesia for AVF creation has been associated with higher
perioerative flow and lower rates of vasospasm resulting in higher rates
of short term patency. Regional anesthesia has not been associated with
perioperative rates of major morbidity or mortality.[@aitken2016;
@siracuse2014]

**What is the role for endovascular creation of AV fistula?**

New methods are now available to perform an upper extremity AVF
endovascularly, although many patients would be suitable candidates, as
of now the usability of these fistulas have not matched that of
surgically placed AVF.[@lok2017]

**When is the newly created dialysis access ready for use?**

A good way to remember this is the rule of 6's. it's ready to use when
the Fistula is 6mm in Diameter, has a flow of 600ml/min, is 6mm from the
surface of the skin and usually takes 6 weeks to mature.

Prosthetic AV accesses can be used as early as 2 weeks postoperatively.
If you use the 3-layer early cannulation grafts, the access can be used
as early as 24 hours after access creation. This is great because it
offers the potential for avoidance of dialysis catheters in patients who
need dialysis immediately.[@glickman2015]

## Maintenance and complications

### Failure to mature

**What are some reasons why an access may fail to mature?**

Sometimes your access may have arterial inflow stenosis. This is
difficult to detect clinically because there will be a palpable thrill,
however, due to the stenosis, the flow is not sufficient enough for
dialysis. In the absence of arterial inflow issues, collateral or large
venous branches can divert blood away from the main access channel
resulting in insufficient flow.

**If the newly created AV fistula is not maturing, what are some
secondary procedures to help with maturation?**

Open procedures include vein patches, interposition vein grafts, vein
transposition to proximal arteries, branch ligations, and vein
superficialization. Endovascular procedures include arterial and venous
angioplasties to improve inflow or outflow issues.[@sidawy2008]

### Access Failure

**Once a dialysis access is created, maintenance of the access is
extremely important. The flow disturbances and hemodynamic changes
associated with AV access creation causes intimal hyperplasia leading to
venous outflow stenosis. This can ultimately lead to access thrombosis
and failure. What are some methods of detecting access failure?**

One way of detecting a well functioning access is a strong thrill at the
arterial anastomosis which continues a few centimeters into the outflow
vein. If you feel a pulsation near the venous outflow, then a stenosis
or thrombosis is likely. If you feel a thrill distal to the area of
pulsation, then you have likely localized your area of stenosis. It is
important to note that you may feel a pulsation at a pseudoaneurysm
independent of venous outflow issues.

Other signs of outflow stenosis are collateral veins or upper extremity
edema.[@padberg2008] This is indicative of venous hypertension likely
secondary to stenosis. You will typically see this in the shoulder area
or anterior chest as a results of subclavian vein stenosis/thrombosis.
Moreover, these high venous pressures as a result of the stenosis can
result in excessive and prolonged bleeding after removal of needles from
the dialysis puncture sites. This is often the first sign of elevated
venous pressures. These patients should undergo a fistulogram to
evaluate for underlying outflow stenosis.[@caromonroig2018]

The most common cause of graft failure in upper extremity fistulas is
venous outflow stenosis and in grafts is venous anastomotic intimal
hyperplasia.[@berman2001; @padberg2008] Diagnostic fistulogram is a very
useful tool to diagnose and treat potential access complications.
Diagnostic fistulogram is often performed with proximal access of the
fistula a few centimeters distal to the anastomosis. Compression of
venous outflow is necessary to evaluate for inflow and anastomotic
issues.[@bountouris2018]

Finally, even patients with normal physical exam can have issues while
on the hemodialysis circuit, such as recirculation. When in doubt, if
there are recurrent issues with hemodialysis, the patient should undergo
a fistulogram to evaluate for occult venous outflow stenosis that may be
missed on other diagnostic modalities.[@sidawy2008]

**What are some endovascular interventions for a failing access?**

First line therapy for outflow stenosis is a simple balloon angioplasty
of the stenosed area.[@berman2001] Insufflation times are generally up
to 2-3 minutes. Treatment of stenosis 2/2 intimal hyperplasia often
require high pressures of 20 ATM or more. However, this is a double edge
sword because this can lead to trauma in the veins stimulating a further
intimal hyperplasia process. Some advocate a cutting balloon before high
pressure dilation. Stenting is also an option to treat residual stenosis
or dissections after balloon angioplasty. Covered stents have shown good
patency results.

Some unique situations include, recurrent cephalic arch stenosis which
may be best treated with bare metal stenting.[@shemesh2008] Proximal
occlusions (i.e. subclavian) may be best treated primarily with a
covered stent.[@agarwal2015; @anaya-ayala2011]

**If endovascular interventions fail, what are some open options for
managing a failing access?**

Generally an interposition graft or patch angioplasty is performed and
the results of the two techniques are largely equivalent.

**If an AV access has ultimately failed and thrombosed, what are your
endovascular options at this point?**

Some endovascular options are catheter directed thrombolysis with about
2-4mg of tPA injected into the clot, followed by balloon angioplasty
(typically an 8mm by 8cm high pressure balloon). A mechanical
thrombectomy device, such as angiojet, can also be used in combination
to thrombolysis.

Alternatively, an open thrombectomy with a thromboembolectomy balloon
and patch angioplasty of venous stenosis areas can also be used.
Moreover, a hybrid approach of open thrombectomy with percutaneous
interventions of venous stenosis areas has been described.

Immediate postoperative thrombosis of an AV graft is likely technical -
inadequate inflow (i.e. small brachial artery) or outflow
stenosis/occlusion. Open revision and thrombectomy is often the best
option.[@paulson2002]

**What are some ways to manage failing AV access in the setting of
ipsilateral vTOS?**

Performing a first rib resection in a hemodialysis patient is high risk
and controversial. However, if there is a prominent external jugular
vein, then there are reports of external to internal jugular vein
transposition offering more in line drainage and access
salvage.[@degiovanni2020]

### Steal Syndrome {#sec-steal-syndrome}

**Earlier, you mentioned steal syndrome, can you explain to us what this
is?**

Steal syndrome is also known as Access Related Hand Ischemis = ARHI. It
is an uncommon but devastating complication of access creation. All
patients with arteriovenous fistulas have some degree of physiologic
steal or reversal of flow in part of the artery distal to the fistula.
However, this is not sufficient enough to cause ischemia. Rather,
ischemia results from inadequate collateral circulation and inability of
peripheral arteries to meet the increased demand. Diseased vessels do
not dilate and stenosis of arteries leads to decreased distal perfusion
pressure. Furthermore, hypotension during dialysis further decreases
perfusion causing symptoms. Steal can be limb threatening and is graded
as follows:

-   Grade 0 - asymptomatic, no flow augmentation or steal

-   Grade 1 - asymptomatic, mild ischemia with signs of cool extremity
    and flow augmentation with access occlusion (May be seen in over
    half of AV access patients)[@leake2015]

-   Grade 2 - moderate/intermittent ischemia that is experienced only
    during dialysis and patients feel claudication.

-   Grade 3 - severe, ischemic pain at rest with tissue loss.

**What are some symptoms and signs of Steal syndrome?**

Symptoms include coolness, parasthesias, rest pain, and weakness. Signs
of steal include cool to touch, pallor, cyanosis, delayed capillary
refill, absent pulses/signals, diminished sensation, weak grip, and in
severe cases ulceration or gangrene. If the patient shows improvement
with access compression, diagnosis is confirmed.

Patients with acute pain and loss of pulses after AVF creation should
first have arterial injury/thrombosis ruled out, but then after
diagnosis of steal syndrome should undergo fistula
ligation.[@schanzer2004; @yevzlin2016]

**When is an intervention necessary to treat steal syndrome?**

You do not need to intervene for grade 0 and 1.[@leake2015] For grade 3
an intervention is mandatory. The goal of treatment includes symptom
resolution and access preservation, and this is achieved by reducing
access flow and increasing distal arterial flow.

The most important finding on duplex ultrasound to evaluate for steal
syndrome is fistula flow rate. High flow rates suggest a primary problem
with the fistula, low or normal flow suggests underlying PVD and inflow
insufficiency as etiology.[@alshakarchi2016; @leake2015] Approximately
5% of steal is secondary to inflow stenosis.

**What are your intervention options for resolving steal syndrome?**

There are multiple ways to manage steal syndrome, detailed as
follows:[@leake2015; @gupta2011]

-   AV Fistula Banding is a simple option to reduce access flow. This is
    done by suture plication, placement of single narrowing tie or wrap
    by constrictive cuff to cause a stenosis in the AV access near the
    arterial anastomosis. A minimally invasive approach is used by the
    MILLER banding which uses an endoluminal 4 or 5mm balloon as a sizer
    and a suture is placed around the access with the balloon inflated.
    This procedure increases arterial inflow towards the hand. Flow
    should be maintained at 600ml/min.

-   Revision using distal inflow (RUDI) involves ligation of the fistula
    at the arterial anastomosis and reestablishment of flow via a more
    distal artery by bypass or vein translocation. This allows for
    decreased flow through the access by reducing the fistula diameter
    and by taking inflow form a smaller vessel. However, ultimately, the
    fistula is placed at risk

-   Proximalizaiton of arterial inflow (PAI) involves ligation of AV
    anastomosis, and the inflow is moved to a more proximal level with a
    prosthetic interposition. Dialysis can be continue via the vein. The
    main advantage is the native artery's continuity.[@zanow2006]

-   Distal revascularization-interval ligation (DRIL) is ultimately
    considered the best option by many vascular surgeons due to the
    excellent results shown. There is an arterial bypass created
    originating proximal to the access and ending distal to the access,
    with ligation of the artery distal to the anastomosis. This prevents
    retrograde flow from distal vessels and allows for a low resistance
    pathway for arterial supply to the hand. DRIL may be particularly
    useful in patients with distal brachial, proximal ulnar/radial
    disease, as this can bypass the underlying stenosis as
    well.[@leake2015]

-   Distal radial artery ligation (DRAL) can be performed for palmar
    arch steal syndrome from radio-cephalic av accesses, to prevent
    reversal of flow in the palmar arch. However, the ulnar artery
    patency needs to evaluated first.

### Neuropathy and Neuropraxia

**What complication often presents like steal syndrome, but with easily
palpable distal pulses?**

Access creation can result in neuropathy. It is important to note that
over 2/3s of the patients have preexisting peripheral neuropathy.
Neuropathy is also graded:

-   Grade 0 - asymptomatic

-   Grade 1 - mild intermittent changes (pain, paresthesia, numbness
    with sensory deficit)

-   Grade 2 - moderate persistent sensory changes

-   Grade 3 - severe sensory changes with progressive motor loss
    (motion, strength, muscle wasting).

Ischemic monomelic neuropathy is rare but occurs acutely after AV access
creation. Within hours of surgery, patients develop acute pain,
weakness, or paralysis of hand and forearm muscles with prominent
sensory loss. However, the hand is warm with palpable pulse or audible
signal in distal radial and ulnar arteries. It is important to note that
pain out of proportion is what differentiates IMN from ARHI. Treatment
is access ligation or emergent augmentation of flow.

### Perioperative neuropraxia

**What are some common technical complications after placement of AV
access?**

Post operative numbness of the thumb, index and middle finger and
weakness of abduction and grip strength may suggest median nerve
neuropraxia and will likely resolve. However, you need to rule out steal
syndrome.[@talebi2011; @vahdatpour2012]

Postoperative hematoma can often just be observed. However, signs of
median nerve compression mandate immediate operative brachial sheath
evacuation or the neurologic deficits may become
permanent.[@padberg2008]

Prosthetic grafts can results in seroma from ultrafiltration of the
graft and most resolve without intervention.

### Bleeding and Aneurysm

**What presentations require urgent revision?**

Fistulas that present with bleeding from a visible ulcer, wet scabbing,
frank infection or acute pseudoaneurysm often require urgent open
revision. Some access may be salvaged, but in acute presentations with
significant risk of life threatening hemorrhage the safest option may be
to ligate the access and place a temporary dialysis access
line.[@galbusera2009]

**Many fistulas develop aneurysms over time. When do fistula aneurysms
require revision?**

-   Pseudoaneurysms often result from trauma due to repeated punctures
    or poor technique

-   True aneurysms result from long standing hemodynamically significant
    outflow stenosis.

Both can lead to cannulation difficulties, increased risk of thrombosis,
pain, bleeding and cosmetic deformities. AV aneurysms should be revised
if they develop skin thinning, ulceration or bleeding. Early skin
changes can be observed. Intervention often requires revision with open
plication/excision or ligation. When isolated to a short segment,
attempts should be made to salvage the fistula.[@al-jaishi2017;
@al-thani2017; @pasklinsky2011]

## Dialysis Catheters

**While ideally every patient would have surgically placed access, many
patients still receive dialysis through catheters. What is the
difference between an acute and chronic hemodialysis catheter?**

Chronic catheters have a subcutaneous cuff at the exit site and tunneled
to the vein. This decreases infection rates and makes them less likely
to become dislodged. Tunneled hemodialysis catheters can be used up to
12 months.

**If catheters cause so much problems such as infection and central
venous stenosis, what would be an indication for them?**

The most common indication would be for urgent hemodialysis. But other
indications include patient who are not operative candidates due to
advanced comorbidities, or patients who are unable to have an AVF or AVG
due to anatomic feasibility. Temporary dialysis access may also be
needed in patients who have just had a peritoneal dialysis catheter
placement or in chronic peritoneal dialysis catheter patients requiring
abdominal or inguinal surgery.

**Which site is the most ideal site for a hemodialysis catheter?**

The right internal jugular vein is preferred because it has the best
patency.

If all traditional access sites are inaccessible, translumbar IVC
catheters may be used as a last resort as salvage. Overall complications
are similar to other permanent dialysis access sites, however obesity is
a relative contraindication due to potential migration into the soft
tissues.

**Every procedure has potential complications. What are the immediate
complications of catheter placement?**

When placed in the internal jugular veins, there is always a chance of a
pneumothorax or hemothorax. Wire embolism can occur is control of the
wire is lost during the procedure. If the guidewire is placed too far,
then there is always a chance of arrhythmia. Thus, the best place for
the wire is through the IVC. With a left internal jugular vein approach,
there is always a risk of thoracic duct laceration. If a leak is
apparent, then the catheter needs to be removed immediately and a
pressure dressing applied.

**How do you manage infected hemodialysis lines?**

Infected hemodialysis lines should be removed. Ideally you should avoid
replacing any lines until blood cultures have been negative for 48hrs,
particularly subsequent permanent
lines[@vascularaccess2006workgroup2006]

## Peritoneal Dialysis

**Although not often managed by the vascular surgeon, we should still be
aware of another method of dialysis in renal failure patients. What are
the indications for peritoneal dialysis?**

Peritoneal dialysis is better tolerated and less disruptive to daily
life, so is often a better option for young, active patients with less
comorbidities. PD can be considered first-line or in patients who are
not candidates for HD, but require high patient engagement and education
and so may not be appropriate for patients with other chronic diseases
limiting independence, unstable housing, cognitive decline or poor
management other medical issues.[@ansari2011]

From a technical standpoint, PD may be difficult in patients who have
had multiple previous open abdominal surgeries, but can be tolerated in
patients who have had minimally invasive or minor abdominal
procedures.[@sinnakirouchenan2011] Long dwell times with glucose
solution can sometimes lead to hyperglycemia. The major reason for
conversion from PD to HD is PD catheter infection.[@li2017]
